README.md

A potential detail is how Rust calls it "Stdout", which in turn is "stdout" https://doc.rust-lang.org/1.29.0/std/io/struct.Stdout.html

Various spellery: the, mac OS, license, etc.

---

README.md
filecoin-proofs/build.rs
sector-base/README.md

Closes #475 
@porcuquine I have not renamed the top level crate, because I realized we already have `filecoin-proofs`, which would make things very confusing. I don't think it matters much, as that is only the placeholder crate and would not get published for now. But let me know if you think otherwise

chore: rename rust-proofs to rust-fil-proofs

---

filecoin-proofs/src/api/internal.rs
filecoin-proofs/src/bin/paramcache.rs
filecoin-proofs/src/lib.rs
parameters.json
storage-proofs/src/circuit/multi_proof.rs
storage-proofs/src/compound_proof.rs
storage-proofs/src/parameter_cache.rs

Closes #477.
Closes #468.
---
**UPDATE**
I added support for verifying key as well. This parallels groth parameter generation throughout.
This means that clients who want only to verify (but not generate) proofs will be able to fetch only the verifying keys they require. This is not necessarily an issue now, but may become one in the future as number and size of circuits grows. Creation of verifying keys still necessarily requires groth params (whether generated or fetched).
**NOTE**
This means that there are now new cache files — just like the groth param files, but with a `.vk` suffix added to the corresponding parameter filename.
I published the initial verifying keys corresponding to the already-published groth params, and updated `parameters.json` here.
---
Unlike the approach …

memory cache for groth params and verifying key

---

filecoin-proofs/src/api/internal.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/sector_builder/helpers/add_piece.rs
filecoin-proofs/src/api/sector_builder/helpers/get_sectors_ready_for_sealing.rs
filecoin-proofs/src/api/sector_builder/helpers/retrieve_piece.rs
filecoin-proofs/src/api/sector_builder/metadata.rs
filecoin-proofs/src/api/sector_builder/mod.rs
filecoin-proofs/src/api/sector_builder/scheduler.rs
filecoin-proofs/src/bin/paramcache.rs
filecoin-proofs/src/bin/paramgen.rs
sector-base/Cargo.toml
sector-base/src/api/bytes_amount.rs
sector-base/src/api/disk_backed_storage.rs
sector-base/src/api/mod.rs
sector-base/src/api/sector_store.rs

Fixes #502 
I found it pretty easy to become units-confused when dealing with sector bytes (padded) vs. sector bytes (not padded).
This PR introduces two [newtype](https://doc.rust-lang.org/1.0.0/style/features/types/newtype.html) wrappers for u64: `UnpaddedBytesAmount` and `PaddedBytesAmount` and modifies the codebase to give/receive values of these types instead of u64.
```rust
let n = UnpaddedBytesAmount(42);
let m = UnpaddedBytesAmount(18);
let a = n + m;
println!("{:?}", u64::from(a)); // 60
let r = PaddedBytesAmount(2);
let b = n + r; // type error
```

distinguish padded/unpadded bytes at the type level

---

storage-proofs/src/drgporep.rs
storage-proofs/src/vde.rs

```
Add the `parents` of node `v` as an argument to `decode_domain_block` to avoid
requesting (and maybe recalculating) them twice for the same node.
`decode_domain_block` is only called in `prove` where the `parents` of node `v`
(`challenge`, in the caller) are already available.
```

drgporep: add parents to `decode_domain_block`

---

filecoin-proofs/src/api/internal.rs
filecoin-proofs/src/api/sector_builder/scheduler.rs

I introduced a bug recently which would cause the FFI-exposed `generate_post` call to call in to the real `internal.rs` `generate_post` function. go-filecoin is not ready for that change yet.
This changeset reverts that change back to the `fake_generate_post` call.

revert to using fake_generate_post instead of real generate_post

---

filecoin-proofs/examples/zigzag.rs
storage-proofs/src/layered_drgporep.rs
storage-proofs/src/proof.rs

Closes #500.
This PR includes a handful of changes which bring the zigzag example closer to what we need as we continue to benchmark and tune sealing with increasingly realistic parameters.
Included here:
- Generate groth params first (for memory reasons).
- Update defaults.
- Add logging to proof generation.
- Receive and use taper parameters.
- Display all challenges.
- Log individual partition proving.

Improve zigzag example for ongoing benchmarks.

---

.circleci/config.yml
filecoin-proofs/examples/ffi/main.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/bin/paramcache.rs

Fixes go-filecoin `#2095`, which you can [read all about here](https://app.zenhub.com/workspaces/filecoin-5ab0036a12f8e82ae4ed60f0/issues/filecoin-project/go-filecoin/2095).
The FFI-exposed `verify_post` function used to accept a u64 which represented sealed sector bytes. go-filecoin had no way of getting sealed sector-bytes from its sector builder, so this API wouldn't have worked without modifying the sector builder interface.
- `verify_post` to accept config value (like `verify_seal`)
- add FFI tests which exercise PoSt verification and generation
- modify `paramcache` to accept two optional flags: `--test-only` and `--include-post` (omits Live parameters and includes PoSt parameters, respectively)
`paramcache` now accepts two optional flags which are used to control Groth parameter …

verify_post should be passed cfg + add FFI tests for PoSt generation/verification

---

Cargo.toml
filecoin-proofs/Cargo.toml
filecoin-proofs/examples/beacon-post.rs
filecoin-proofs/examples/drgporep-vanilla.rs
filecoin-proofs/examples/encoding.rs
filecoin-proofs/examples/zigzag.rs

The CPU and memory profilers don't seem to play nice together (at least in my local tests), I'm getting a
```
Check failed: f->header.magic == Magic(kMagicAllocated, &f->header): bad magic number in Free()
Aborted (core dumped)
```
so I'm deliberately redefining `start_profile` to make sure the two features are not used together (as far as I've seen `cargo` doesn't support mutually exclusive features).

examples: zigzag: add heap profiler

---

filecoin-proofs/src/bin/paramfetch.rs
filecoin-proofs/src/bin/parampublish.rs
filecoin-proofs/src/param.rs

fixes: https://github.com/filecoin-project/rust-fil-proofs/issues/511
removed check subcommands and simplified tool use (run `paramfetch`, not `paramfetch fetch`)
moved the commands themselves to their own functions with `Result` return type so i can use `?`
made output verbiage a bit more consistent

paramfetch: validate all parameters

---

filecoin-proofs/examples/ffi/main.rs
filecoin-proofs/src/api/internal.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/post_adapter.rs
filecoin-proofs/src/api/responses.rs
filecoin-proofs/src/api/sector_builder/mod.rs
filecoin-proofs/src/api/sector_builder/scheduler.rs

Fixes the rust-fil-proofs side of #505. Note that the go-filecoin CGO code will need to integrate with this new API and the `submitPoSt` message will need to be modified to accommodate the variable number of SNARK proof outputs. That's next on my list of things to do.
Our current VDF PoSt construction allows us to prove a fixed number of sectors (that number is 2, or `POST_SECTORS_COUNT`). API consumers don't know about this; they want to provide a variable number of replica commitments when proving and receive a proof in return.
To provide the API that our consumers want, we need to adapt PoSt generation and verification FFI function calls (which accept a variable number of replica commitments) to our internal PoSt generation and verification operations (which accept exactly 2 replica …

adapter layer to accommodate fixed "sectors count" in VDF PoSt

---

storage-proofs/Cargo.toml
storage-proofs/src/crypto/feistel.rs

before
```
replication_time: 4.609915269s, target: stats, place: filecoin-proofs/examples/zigzag.rs:193 zigzag, root: filecoin-proofs
replication_time/byte: 4.395µs, target: stats, place: filecoin-proofs/examples/zigzag.rs:194 zigzag, root: filecoin-proofs
```
after
```
replication_time: 3.887283333s, target: stats, place: filecoin-proofs/examples/zigzag.rs:193 zigzag, root: filecoin-proofs
replication_time/byte: 3.707µs, target: stats, place: filecoin-proofs/examples/zigzag.rs:194 zigzag, root: filecoin-proofs
```

perf(feistel): use blake2b_simd

---

storage-proofs/Cargo.toml
storage-proofs/src/crypto/feistel.rs
storage-proofs/src/hasher/blake2b.rs
storage-proofs/src/zigzag_drgporep.rs
storage-proofs/src/zigzag_graph.rs

While trying to benchmark large(r) sectors, I (eventually) discovered that `setup` was hanging. The root cause turns out to be the known issue that our Feistel implementation permutes elements of type `u32`. Since we need `expansion_degree` (currently 8) elements per node, that means we can handle only up to 2^27 nodes. This corresponds to sectors of size 2^32 (2^27 * 32), which is 4GiB .
The simple solution is to extend to use `u64`. In a perfect world, we might be able to select alternate generic implementations for `u32` or `u64` depending on the actual sector size, but that will/would be somewhat tricky and may not be worth it. Hopefully any benefits of smaller cache keys can be implemented just at the level of the cache while leaving the Feistel implementation to use `u64`. For now, …

Larger sectors

---

filecoin-proofs/Cargo.toml
filecoin-proofs/examples/zigzag.rs

This PR contains small changes I needed while benchmarking replication and proving on a high-memory machine.
Specifically:
- Optionally allow suppression of temp file, giving more control (should be more configurable later) over where the data resides.
- Dump vanilla proofs so they can be reused for groth proving without replicating again (expensive!). We can't yet use these dumped proofs, but if I make it through a very long replication I don't want to lose the resulting artifact. Ability to restart groth proving without replication can be added when needed.
- Don't generate random data, just zero the mmapped data by extending the file. This will save a lot of time on expensive machines.

More zigzag example tweaks

---

storage-proofs/Cargo.toml
storage-proofs/src/circuit/kdf.rs
storage-proofs/src/crypto/kdf.rs
storage-proofs/src/crypto/sloth.rs
storage-proofs/src/drgporep.rs
storage-proofs/src/fr32.rs
storage-proofs/src/hasher/digest.rs
storage-proofs/src/hasher/pedersen.rs
storage-proofs/src/hasher/types.rs
storage-proofs/src/test_helper.rs
storage-proofs/src/vde.rs

- Avoid allocations by updating the hasher directly, instead of allocating a vector.
- Use [`blake2s_simd`](https://github.com/oconnor663/blake2s_simd) to speed up the actual hashing operations.
- Avoid some conversions from `Fr` to `FrRepr` and back.
Performance Improvements
- Testcase: `32 MB - zigzag default`
| variant                  | replication time |
|--------------------------|------------------|
| master |    178.938245178s, |
| this branch    |  169.802207285s |
Note: this currently uses an unpublished version of https://github.com/oconnor663/blake2s_simd

feat(vde): improve performance of create_key

---

filecoin-proofs/examples/drgporep-vanilla-disk.rs
filecoin-proofs/examples/drgporep-vanilla.rs
filecoin-proofs/examples/zigzag.rs
storage-proofs/src/circuit/drgporep.rs
storage-proofs/src/drgporep.rs
storage-proofs/src/layered_drgporep.rs
storage-proofs/src/vde.rs

Should fix #537 
Speed improvements on my machine for `1MB` data zigzag (`cargo run -p filecoin-proofs --release --example zigzag -- --m 5 --expansion 8 --layers 10 --challenges 5 --size 1024 --no-bench`)
- `master`:  vanilla_proving_time: `495.295015ms`
- `perf-vanilla-proving`: vanilla_proving_time: `4.295946ms`

perf(drgporep): decode_domain_block: avoid data allocations

---

.circleci/config.yml
filecoin-proofs/src/bin/paramcache.rs
parameters.json

Fixes #510 
- dig updated Groth param cache-keys, so we needed to regen parameters
- adding PoSt params to `parameters.json`
- enabling PoSt (soon) in go-filecoin will require PoSt Groth params

publish v10 Groth parameters + paramcache always generates PoSt parameters

---

filecoin-proofs/examples/zigzag.rs
storage-proofs/src/circuit/metric/mod.rs
storage-proofs/src/circuit/mod.rs
storage-proofs/src/circuit/zigzag.rs

Closes #546.
For more context, see description at #545.
This PR implements a new constraint system which never calls the closures passed `alloc` and `alloc_input`. Instead it just gather the data required to gather our 'bench' metrics: number of inputs, number of constraints, and a printed representation of the circuit.

Add MetricCS constraint system for blank_circuit-compatible metrics.

---

filecoin-proofs/src/bin/paramfetch.rs
filecoin-proofs/src/param.rs

Fixes [go-filecoin issue 2041](https://github.com/filecoin-project/go-filecoin/issues/2041).
1. `paramfetch` didn't set any curl timeout, so IPFS gateway problems (post-connection) meant `paramfetch` would hang indefinitely
1. `paramfetch` didn't give users any diagnostic information from curl, such as URL, request metadata, transfer progress, etc.
This PR adds a new flag to `paramfetch` which makes it print curl-related stuff to stdout:
```
07:42 $ yes | ./target/release/paramfetch --all --retry --verbose
checking 8 parameter files...
checking: v10-vdf-post-c8ddc8e74f9c2ed6a4bc83df171a9e9e84e242cf6e48e20f71585106fa8a3ce6.vk
does parameter file exist... yes
is parameter file valid... yes
checking: v10-zigzag-proof-of-replication-b8f3290335d11af86f8193cc2c3bbf451b4b2cc33e59e8ecad060999f3beb …
```

various improvements to paramfetch

---

storage-proofs/Cargo.toml

Lock `merkle_light` dependency to the current `master` commit to land some API-braking changes in https://github.com/filecoin-project/merkle_light/pull/13, https://github.com/filecoin-project/rust-fil-proofs/pull/529 will restore it to `master` once everything is working as expected (or preferably, we'll cut a stable release for `merkle_light` to stabilize this dependency).

deps: lock `merkle_light` dependency to the current `master` commit

---

drop-struct-macro-derive/.gitignore
drop-struct-macro-derive/Cargo.toml
drop-struct-macro-derive/LICENSE-APACHE
drop-struct-macro-derive/LICENSE-MIT
drop-struct-macro-derive/README.md
drop-struct-macro-derive/src/lib.rs
filecoin-proofs/Cargo.toml
filecoin-proofs/src/api/responses.rs

Dropping memory is a large part of the reposonses FFI code. With
this new macro `#[derive(DropStructMacro)]` the `Drop` implementation
will be auto-generated based on the struct.
Example:
```rust
pub struct FFIStagedSectorMetadata {
pub sector_access: *const libc::c_char,
pub sector_id: u64,
pub pieces_len: libc::size_t,
pub pieces_ptr: *const FFIPieceMetadata,
// must be one of: Pending, Failed, Sealing
pub seal_status_code: FFISealStatus,
// if sealing failed - here's the error
pub seal_error_msg: *const libc::c_char,
}
```
Will automatically create:
```rust
impl Drop for FFIStagedSectorMetadata {
fn drop(&mut self) {
unsafe {
free_c_str(self.sector_access as *mut libc::c_char);
drop(Vec::from_raw_parts(
self.pieces_ptr as *mut FFIPieceMetadata,
self.pieces_len,
self.pieces_len,
)); …
```

Adding a macro to free memory in the FFI automatically

---

filecoin-proofs/src/bin/paramfetch.rs

Fixes #556 
- fix short flag for `--verbose` option, which should have been `-v` and not `-a`

shortflag for --verbose should be -v, not -a

---

filecoin-proofs/examples/drgporep.rs
parameters.json
storage-proofs/src/circuit/drgporep.rs
storage-proofs/src/circuit/por.rs
storage-proofs/src/circuit/zigzag.rs
storage-proofs/src/drgraph.rs
storage-proofs/src/hasher/blake2b.rs
storage-proofs/src/hasher/blake2s.rs
storage-proofs/src/hasher/digest.rs
storage-proofs/src/hasher/pedersen.rs
storage-proofs/src/hasher/sha256.rs
storage-proofs/src/hasher/types.rs

Basic tests are passing. Needs some more checks
- make por and drgporep circuits abstract over the hasher
- implement blake2s hasher using blake2s_simd
Ref #531

feat(storage-proofs): zizag, drgporep and por abstract over the hasher in circuits

---

filecoin-proofs/src/api/mod.rs
storage-proofs/src/vdf.rs

Fixes #568 
- spelling "misspelling" was the most difficult part of this PR

fix misspellings of "verifiable" and "verify"

---

storage-proofs/Cargo.toml
storage-proofs/src/drgporep.rs
storage-proofs/src/hasher/blake2s.rs
storage-proofs/src/hasher/digest.rs
storage-proofs/src/hasher/pedersen.rs
storage-proofs/src/hasher/sha256.rs
storage-proofs/src/hasher/types.rs
storage-proofs/src/merkle.rs
storage-proofs/src/vde.rs

~Blocked on https://github.com/filecoin-project/merkle_light/pull/13, after that is merged the dependency here should point to `merkle_light/master`.~
-----------------------------------------------------------
This is now dropping the allocated memory an order of magnitude:
```
Total: 309.4 MB
309.0  99.9%  99.9%    309.0  99.9% ::allocate_in (inline) /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/raw_vec.rs:109
0.3   0.1% 100.0%      0.3   0.1% ::reserve_internal (inline) /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/raw_vec.rs:683
0.1   0.0% 100.0%      0.1   0.0% sapling_crypto::jubjub::JubjubBls12::new (inline) ??:0
Total: 19.4 MB
13.0  67.1%  67.1%     13.0  67.1% ::allocate_in (inline) /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/raw_vec. …
```

use `MmapStore` for `MerkleTree` generation

---

storage-proofs/src/drgraph.rs
storage-proofs/src/error.rs
storage-proofs/src/vde.rs

The node size in the depth robust graph was already hard-coded to 32 bytes,
but this value was still used on a few occasions as a magic number. Change
the code to rely on those 32 bytes which is defined by the NODE_SIZE constant.
I'm not sure if I should do those kind of refactors without having all the context,
please let me know.

refactor(storage_proofs): make fixed node size in drgraph more explicit

---

sector-base/README.md

Delete the outdated link for sector-base

Delete the outdated link

---

storage-proofs/src/drgraph.rs
storage-proofs/src/vde.rs

Also adding documentation that a node without parents is indicated by
the first parent being the node itself.
I'd like to note that something here is strange though. When I was looking into "unsuckifying" the code, i first thought i could change the if statement to `node != 0` as only the first node doesn't have any parents. But that  would make the tests fail (more specifically the `zigzag_drgporep::tests::extract_all_*`ones).
It turns out that there's also parents where every element is a `2`, so it's not the first node, but it's self-referencing itself nonetheless. From reading the code at https://github.com/filecoin-project/rust-fil-proofs/blob/808dc884642acbf7b78b282eb7d933c7cc2cc3a7/storage-proofs/src/drgraph.rs#L118 I thought only the first node has no parents.

refactor(storage_proofs): move condition outside of the loop

---

filecoin-proofs/examples/ffi/main.rs
filecoin-proofs/src/api/internal.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/sector_builder/helpers/add_piece.rs
filecoin-proofs/src/api/sector_builder/mod.rs
filecoin-proofs/src/api/sector_builder/scheduler.rs
sector-base/src/api/disk_backed_storage.rs
sector-base/src/api/sector_store.rs
sector-base/src/io/fr32.rs
storage-proofs/benches/preprocessing.rs

- `write_padded` now polymorphic over `Read`, which allows stream processing of inbound bytes
- `write_and_preprocess` also polymorphic over `Read` for same reasons
- `write_and_preprocess` consumers (e.g. FFI) can pass a `File`, which satisfies `Read`
- FFI consumers provide path, which can point to a named pipe or normal file
- Buffering client pieces completely into memory for padding is bad
- We'd like to stream to `write_padded` from the go-filecoin `DagReader` (we do so by way of a named pipe)

add piece through FFI w/out buffering piece into memory

---

bench.config.toml
src/bin/bencher.rs

fixes: https://github.com/filecoin-project/rust-fil-proofs/issues/536
allows additional parameters to be passed to the benchmarks, for now specifically zigzag
allows a benchmark to fail and continue to try to run the rest
allows non-json output to not break a benchmark

zigzag benching

---

storage-proofs/src/config.rs
storage-proofs/src/zigzag_graph.rs

fixes: https://github.com/filecoin-project/rust-fil-proofs/issues/586
changes storage-proofs config to store configuration as string values
to get a boolean value out of the config, use `get_config_bool`

store config as strings

---

storage-proofs/Cargo.toml
storage-proofs/benches/encode.rs

You can run it via `cargo bench -- "encode single node"`.
Closes #530.

feat(storage_proofs): Add benchmark for encoding a single node

---

filecoin-proofs/examples/ffi/main.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/responses.rs
filecoin-proofs/src/api/sector_builder/mod.rs
filecoin-proofs/src/api/sector_builder/scheduler.rs

We change the argument of `get_max_user_bytes_per_staged_sector` from a `SectorBuilder` to a `ConfiguredStore`, since we need to use this function in a place that has access to the `ConfiguredStore`, but not the `SectorBuilder`.

Change argument to get_max_user_bytes_per_staged_sector

---

storage-proofs/src/compound_proof.rs
storage-proofs/src/config.rs

This should fix https://github.com/filecoin-project/rust-fil-proofs/issues/585. But this is just a temporary solution, as people may be surprised the fact that `NUM_PROVING_THREADS` specified in the toml file should be a string. To make the config work for value other than string, we may have to change the config to a struct. Should I implement that or any other ideas?

make NUM_PROVING_THREADS configurable

---

storage-proofs/src/error.rs
storage-proofs/src/piece_inclusion_proof.rs

Implements first part of #592.
Probably needs some interface tweaks for integration.
For now, only aligned proofs are supported. However, my goal was to provide an interface compatible with later addition of unaligned proofs.
In particular,
- Before packing, call `PieceSpec::compute_packing` to receive a packing list and proof size.
- Packing list provides the ordering in which arbitrary piece segments should be added to the sector.
- Proof size allows for comparison of alternate alignments to evaluate the cost (in proof size) of padding decisions.
- Proofs always contain size and position of the piece. (This can be two 64-bit numbers. If we want to optimize for proof size of the aligned case, we can add some kind of type tag. If we want to compress somehow, we can.) With size and …

Piece Inclusion Proof (PIP)

---

filecoin-proofs/examples/ffi/main.rs
filecoin-proofs/src/api/internal.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/post_adapter.rs
filecoin-proofs/src/api/responses.rs
filecoin-proofs/src/api/sector_builder/helpers/seal.rs
filecoin-proofs/src/api/sector_builder/metadata.rs

Makes incremental progress towards multiple sector size epic.
- modify FFI-exposed verification functions' types to accept proofs of different sizes
- write some functions to infer proof partitions from number of bytes in proof
I put this changeset together as quickly as I could in order to unblock @porcuquine. It's not of the highest quality (see over usage of `Vec<u8>`), but it can be improved upon in subsequent PRs.
- We should replace all the `Vec<u8>` stuff with a `PoStProof` enum with members for each proof length. Mixing up the length of these byte vectors is going to bite (byte?) us later.

support variable-length proofs

---

storage-proofs/src/circuit/apex_commitment.rs
storage-proofs/src/circuit/mod.rs

This PR implements a component we can use to avoid rehashing the top (apex) part of a merkle tree repeatedly when performing many inclusion proofs. I will write the larger plan (which @nicola and I have been discussing in detail since Friday) up separately.
I'm submitting this PR now because what it contains is independently meaningful and can be reviewed independently — even though not used for our proofs yet. We can iterate on the interface, etc. if necessary when we get to the full optimization.
The idea here is that we can create a vector commitment to a power-of-2 number of `Fr` values and hash them together to form a single root more cheaply than by creating a complete binary merkle tree. (If/when we have more generators, we can do this in fewer pedersen hashes. For now, we still …

Apex merkle commitment

---

filecoin-proofs/examples/zigzag.rs
filecoin-proofs/src/api/internal.rs
storage-proofs/src/batchpost.rs
storage-proofs/src/beacon_post.rs
storage-proofs/src/circuit/drgporep.rs
storage-proofs/src/circuit/por.rs
storage-proofs/src/circuit/porc.rs
storage-proofs/src/circuit/vdf_post.rs
storage-proofs/src/circuit/zigzag.rs
storage-proofs/src/compound_proof.rs
storage-proofs/src/drgporep.rs
storage-proofs/src/layered_drgporep.rs
storage-proofs/src/merklepor.rs
storage-proofs/src/porc.rs
storage-proofs/src/proof.rs
storage-proofs/src/vdf_post.rs

This lays the groundwork for ensuring proofs meets some minimum challenge requirement, regardless of how many partitions are used. Previously we had no way of enforcing aggregate requirements. This corrects that.
It adds a general mechanism allowing `Requirements` to be specified to any `ProofScheme`. These requirements are passed as a parameter to a new `satisifies_requirements` trait method. This method also receives public parameters and number of partitions. This allows it to determine whether the proof's public parameters meet requirements when divided into a given number of partitions.
Also included is a simple `ChallengeRequirements` impelementation for layered proofs. This ensures that the total number of challenges across all partitions is at least some minimum. For now, I set …

Add CompoundProof Requirements + ChallengeRequirements

---

scripts/package-release.sh
scripts/publish-release.sh

this is step 1ii of https://github.com/filecoin-project/go-filecoin/issues/2441
easier access to publishing `tar`s will remove the need for go-filecoin to understand the file structure of its dependencies

break out packaging from publishing script

---

filecoin-proofs/build.rs

Fixes #617 
- we added rocksdb dependency recently, which means that the staticlib that we produce needs to be linked along with the C++ stdlib
- our packaging scripts don't build the pkg-config `Libs` list dynamically; this list needs to be updated every time the dependencies change
- add `libstdc++` to hard-coded list of deps
We should [really be constructing that dependency list by consuming Rust compiler output](https://app.zenhub.com/workspaces/filecoin-5ab0036a12f8e82ae4ed60f0/issues/filecoin-project/rust-fil-proofs/616).

add libstdc++ to deps list to accommodate rocksdb

---

filecoin-proofs/src/api/internal.rs
filecoin-proofs/src/bin/paramcache.rs
filecoin-proofs/src/bin/paramgen.rs
filecoin-proofs/src/bin/parampublish.rs
filecoin-proofs/src/param.rs
parameters.json
sector-base/src/api/porep_config.rs
sector-base/src/api/sector_size.rs
storage-proofs/src/settings.rs

Toward #422.
Included in this PR:
- Calculate PoRep challenges based on number of partitions, such that minimum total challenges are met. The minimum is a constant across all sector sizes and proof sizes.
- Generate parameters for all valid sector-size/partitions combinations. As of now, all combinations are valid, so all are generated.
- Sort parameters when publishing so re-publishing without changes never produces a diff. (cc: @sidke).
- Reduce default value of `NUM_PROVING_THREADS` to 1, since larger values may be problematic on machines with few cores. (This will begin to matter as we add partitions.)
NOTE: I published parameters here to verify that they had *not* changed. However, because `parameters.json` did not previously have a canonical ordering, this produced a diff in the …

Calculate challenges per partition, ensuring total minimum is met.

---

filecoin-proofs/Cargo.toml
filecoin-proofs/src/bin/paramfetch.rs
filecoin-proofs/src/param.rs

Reverts filecoin-project/rust-fil-proofs#628
The aforementioned PR adds a linker dependency on libcurl and this results in libcurl symbols appearing in our `libfilecoin_proofs.a` archive file. Developers who want to build e.g. go-filecoin against `libfilecoin_proofs.a` will need to have libcurl on their linker path.
```
$ nm -gC target/release/libfilecoin_proofs.a  | grep url | head -n 10
00000000000123b0 T _$LT$curl..easy..handler..Easy2$LT$H$GT$$GT$::get_mut::hd75faf5c99248079
0000000000020420 T _$LT$curl..easy..handler..Easy2$LT$H$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h1e6caa5a03813683
U _curl_easy_cleanup
U _$LT$curl..error..Error$u20$as$u20$core..fmt..Debug$GT$::fmt::h129f9d43596a4671
U _$LT$curl..easy..list..List$u20$as$u20$core..ops..drop..Drop$GT$::drop::h02023abf58e11e43 …
```

Revert "Add progress bar during parameter download"

---

filecoin-proofs/examples/ffi/main.rs
filecoin-proofs/src/api/internal.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/post_adapter.rs
filecoin-proofs/src/api/responses.rs
filecoin-proofs/src/bin/paramcache.rs
filecoin-proofs/src/bin/paramgen.rs
sector-base/src/api/bytes_amount.rs
sector-base/src/api/disk_backed_storage.rs
sector-base/src/api/mod.rs
sector-base/src/api/porep_config.rs
sector-base/src/api/porep_proof_partitions.rs
sector-base/src/api/post_config.rs
sector-base/src/api/post_proof_partitions.rs
sector-base/src/api/sector_class.rs
sector-base/src/api/sector_size.rs

Supports go-filecoin issue `#2591`.
- FFI consumers need to know how to chunk the proofs returned from `generate_post`
- FFI consumers need to tell us how to chunk the proofs provided to `verify_post`
- FFI test was not exercising `verify_seal` FFI function
- Replace most of the `FFI*` enums, as they weren't providing any value (hat tip @porcuquine)
- Remove notion of `Live` versus `Test` `SectorClass`
- Remove notion of `Live` versus `Test` (`PoStConfig` and `PoRepConfig`)
- FFI functions which need number of proof partitions receive number of proof partitions
- FFI functions whose callers need to know number of proof partitions (for chunking) now receive number of proof partitions

accept and return proof partitions through FFI + eliminate FFI enums + add seal verification to FFI test 

---

filecoin-proofs/build.rs

We removed RocksDB, so we can now remove libstdc++ from our pkg-config file

remove dependency on libstdc++

---

storage-proofs/Cargo.toml
storage-proofs/benches/drgraph.rs
storage-proofs/benches/parents.rs
storage-proofs/src/circuit/drgporep.rs
storage-proofs/src/drgporep.rs
storage-proofs/src/drgraph.rs
storage-proofs/src/vde.rs
storage-proofs/src/zigzag_graph.rs

In order to save some allocations, the vector for parents is
allocated outside the call. This is on optimisation for loops
where that vector can be re-used in several parents() calls.
It's not clear that it really improves the performance. When
running the benchmark for encoding a single node, there's no
significant difference when this change is applied:
```
group                             HEAD2                                  less-alloc2
-----                             -----                                  -----------
encode single node/Blake2s/10     1.00     13.1±0.63µs        ? B/sec    1.01     13.2±0.62µs        ? B/sec
encode single node/Blake2s/3      1.00     11.8±0.52µs        ? B/sec    1.07     12.7±0.59µs        ? B/sec
encode single node/Blake2s/5      1.00 …
```

perf(storage_proofs): Allocate outside the parents() call

---

filecoin-proofs/src/api/internal.rs
storage-proofs/Cargo.toml
storage-proofs/src/settings.rs

Hallelujah, the problem necessitating the fakery fixed itself, probably during the epic rectification in #517.

Unfake PoSt verification.

---

filecoin-proofs/examples/ffi/main.rs
filecoin-proofs/src/api/internal.rs
filecoin-proofs/src/api/sector_builder/helpers/add_piece.rs
filecoin-proofs/src/api/sector_builder/helpers/get_sectors_ready_for_sealing.rs
filecoin-proofs/src/api/sector_builder/helpers/retrieve_piece.rs
filecoin-proofs/src/api/sector_builder/metadata.rs
filecoin-proofs/src/api/sector_builder/mod.rs
filecoin-proofs/src/api/sector_builder/pieces.rs
filecoin-proofs/src/api/sector_builder/scheduler.rs
sector-base/src/api/bytes_amount.rs

- fixes `compute_destination_sector_id` to be deterministic by ordering sectors before selecting
- `add_piece` now packs pieces naively into sectors, zeroing their data in from the left and out to the right to ensure the existence of a yet to be calculated `comm_p` in the merkle tree of the sector
- `retrieve_piece` also accounts for this new padding

piece packing

---

.circleci/config.yml
filecoin-proofs/build.rs

A recent change to the rust-fil-proofs codebase introduced a link-time dependency on CoreFoundation for OSX builds. 
This PR adds that dependency to the pkg-config file which our build generates. This PR also updates the CircleCI config to output (to stdout) the linker command required to link libfilecoin_proofs.a in OSX and in Linux environments (for debugging).

link CoreFoundation framework

---

storage-proofs/src/piece_inclusion_proof.rs

We can reduce the size of a `PieceInclusionProof` by removing the `sector_leaves` field. This requires removing the redundant check during verification.
We *do* need both `sector_leaves` and `piece_leaves` when verifying — because these values are part of the claim which must be proved.
This field was a remnant of initial development. The apparent need to include it (in a previous implementation) is replaced by the requirement to pass `piece_leaves` to verification. Note that the latter is missing from the spec, which should be changed to reflect both.

Remove superfluous piece_leaves from PieceInclusionProof.

---

CONTRIBUTING.md

Closes #516.
This includes the policy summary described in #516 and explicit GitHub button-pushing strategy to minimize approval churn. @dignifiedquire I believe what I described for the latter is what you tested and verified conforms with our intent.
Please feel free to extend, edit, polish as you see fit.

docs(contributing): add Git merge policy.

---

storage-proofs/src/batchpost.rs
storage-proofs/src/beacon_post.rs
storage-proofs/src/challenge_derivation.rs
storage-proofs/src/circuit/apex_commitment.rs
storage-proofs/src/circuit/beacon_post.rs
storage-proofs/src/circuit/kdf.rs
storage-proofs/src/circuit/pedersen.rs
storage-proofs/src/circuit/por.rs
storage-proofs/src/circuit/porc.rs
storage-proofs/src/circuit/ppor/mod.rs
storage-proofs/src/circuit/sloth.rs
storage-proofs/src/circuit/test/mod.rs
storage-proofs/src/circuit/vdf_post.rs
storage-proofs/src/circuit/xor.rs
storage-proofs/src/circuit/zigzag.rs
storage-proofs/src/compound_proof.rs
storage-proofs/src/drgporep.rs
storage-proofs/src/drgraph.rs
storage-proofs/src/example_helper.rs
storage-proofs/src/fr32.rs
storage-proofs/src/hasher/pedersen.rs
storage-proofs/src/layered_drgporep.rs
storage-proofs/src/merklepor.rs
storage-proofs/src/piece_inclusion_proof.rs
storage-proofs/src/porc.rs
storage-proofs/src/vdf_post.rs
storage-proofs/src/zigzag_drgporep.rs

Relates to Issue #390 
- Removes `panic`-able `unwrap`s from the `storage-proofs` subcrate.
- Does not add clippy lint for disallowing unwrapping because many `unwrap`s can't `panic`.

refactor(storage-proofs): remove panic-able unwraps

---

filecoin-proofs/src/lib.rs

The safe API requires (as input) and returns (as output) types which are not themselves exported.
Export all the types, and export the constant required when chunking proofs.

bug(expose the types required/produced by the safe API)

---

filecoin-proofs/src/bin/paramfetch.rs
filecoin-proofs/src/param.rs

paramfetch default ipfs gateway(https://ipfs.io) is blocked by [GFW](https://en.wikipedia.org/wiki/Great_Firewall) in China. this PR can specific ipfs gateway.

feat(filecoin-proofs): allow paramfetch to use a specific ipfs gateway

---

storage-proofs/src/settings.rs

Follow-up to https://github.com/filecoin-project/rust-fil-proofs/pull/689 to avoid Clippy warning.

fix(storage-proofs): conditionally include of SP_LOG

---

storage-proofs/Cargo.toml

Uses https://github.com/filecoin-project/merkle_light/pull/21.
----------------------------------
Bench summary: A replication with a sector size of 8 GiB is now reduced from a max RSS of 32 GiB (4 sector sizes) to 24 GiB (3 sector sizes). The replications time itself is considerably reduced also (the bench times are not a faithful representation of MT build time since ~60% of replication time is actually spent in the encoding phase, so the 7 minutes reduction actually represents something like ~35% reduction in MT build time). The Criterion bench is giving a strong regression in performance since the new MT build is optimized for big sector sizes, so we need to either adjust it for small sectors (if they are representative of actual use) or increase the number of nodes in those …

dep(storage-proofs): update merkletree to 0.7

---

storage-proofs/Cargo.toml

This reverts commit 4d520ea247eaebbc06ae1cca28cfc49cf1f2b4c4.
Temporary fix for https://github.com/filecoin-project/rust-fil-proofs/issues/713.

Revert "dep(storage-proofs): update merkletree to 0.7"

---

filecoin-proofs/benches/preprocessing.rs

Fixes #717 
A recent change causes the type checker to overflow due to the `as_ref()` call being ambiguous.
This changeset modifies the way that the `&mut Read` is constructed from the owned vector such that the type checker doesn't explode.
- [here](https://github.com/rust-lang/rust/issues/57854)
- [here](https://stackoverflow.com/questions/50189976/why-do-i-get-overflow-evaluating-the-requirement-sized-when-using-tokio-ios)

bugfix(avoid ambiguous as_ref call)

---

storage-proofs/Cargo.toml
storage-proofs/src/crypto/pedersen.rs
storage-proofs/src/hasher/pedersen.rs
storage-proofs/src/lib.rs
storage-proofs/src/vdf_post.rs

For tests purposes only. Blatantly commenting out to make it build.
Downgraded `storage-proofs`, `filecoin-proofs` pending.

downgrade bitvec to v0.5

---

storage-proofs/src/drgraph.rs

I forgot to add the sector size computation for DRGraph.
This PR adds the sector size computation for DRGraph.

DRGraph ParameterSetMetadata is missing `sector_size

---

filecoin-proofs/examples/zigzag.rs

Closes https://github.com/filecoin-project/rust-fil-proofs/issues/733.

fix(filecoin-proofs): invert no-bench default in zigzag example

---

storage-proofs/src/layered_drgporep.rs

I'm not sure how many _trillion_ times I've read that log and this is the first time I've noticed it.

Fix log in encoding

---

filecoin-proofs/Cargo.toml
filecoin-proofs/src/fr32.rs

Towards fixing https://github.com/filecoin-project/rust-fil-proofs/issues/749.
Still not the original values in https://github.com/filecoin-project/rust-fil-proofs/pull/435#issuecomment-453785468 but we're already in the same order of magnitude.

fix(filecoin-proofs): downgrade bitvec to v0.5

---

fil-proofs-tooling/Cargo.toml
fil-proofs-tooling/src/bin/benchy/main.rs
fil-proofs-tooling/src/bin/benchy/zigzag.rs

We'd like to couple the ZigZag benchmarker (benchy) to a specific Git SHA of the ZigZag implementation. Moving it out of rust-filbase allows us to easily do that.
This PR moves benchy from rust-filbase into rust-proofs.

feat(move zigzag/benchy over to rust-proofs)

---

fil-proofs-tooling/src/bin/benchy/zigzag.rs
filecoin-proofs/examples/zigzag.rs

The comparison is between the decoded and the encoded data, so the check should be not equal. 
Closes #768

fix(examples): assert not equal after decoding

---

fil-proofs-tooling/src/bin/micro.rs

Makes incremental progress towards #761.
This PR modifies the micro benchmarker to output JSON. It omits properties with no available value, e.g. R^2, instead of emitting `0.0`. It also adds throughput to the JSON.
```json
[
// ...
{
"mean": null,
"med_abs_dev": null,
"median": null,
"name": "preprocessing/write_padded/256000",
"r_2": null,
"samples": 2,
"slope": null,
"std_dev": null,
"throughput": {
"end": 151.93,
"start": 150.32,
"unit": "MiB/s"
},
"throughput_med": {
"unit": "MiB/s",
"value": 150.64
},
"time": {
"end": 1624.2,
"start": 1606.9,
"unit": "us"
},
"time_med": {
"unit": "us",
"value": 1620.7
}
},
// ...
{
"mean": null,
"med_abs_dev": null,
"median": null,
"name": "xor-circuit/synthesize",
"r_2": null,
"samples": 20,
"slope": null,
"std_dev": null,
"throughput": null, …
```

JSON output for micro benchmarks

---

fil-proofs-tooling/scripts/benchy.sh

If `env time` is GNU time, then make sure we run `env time` instead of `time`.

bug(prefix time binary with env)

---

fil-proofs-tooling/scripts/benchy.sh
fil-proofs-tooling/src/bin/benchy/zigzag.rs
fil-proofs-tooling/src/bin/micro.rs
fil-proofs-tooling/src/metadata.rs

This PR changes the JSON property-casing from `camelCase` to `kebab-case`:
```json
{
"git": {
"hash": "bfb453a9a7796a535d94696826182c416bac00c8",
"date": "2019-08-07T01:35:27Z"
},
"system": {
"system": "Darwin",
"release": "18.7.0",
"version": "Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64",
"architecture": "x86_64",
"processor": "Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz",
"processor-base-frequency-hz": 3100,
"processor-max-frequency-hz": 4100,
"processor-features": "FeatureInfo { eax: 591593, ebx: 101713920, edx_ecx: SSE3 | PCLMULQDQ | DTES64 | MONITOR | DSCPL | VMX | SMX | EIST | TM2 | SSSE3 | FMA | CMPXCHG16B | PDCM | PCID | SSE41 | SSE42 | X2APIC | MOVBE | POPCNT | TSC_DEADLINE | AESNI | XSAVE | OSXSAVE | AVX | F16C | RDRAND | FPU | …
```

feat(kebab-case instead of camelCase)

---

fil-proofs-tooling/src/bin/benchy/zigzag.rs
filecoin-proofs/examples/zigzag.rs
filecoin-proofs/src/singletons.rs
storage-proofs/benches/pedersen.rs
storage-proofs/src/circuit/apex_commitment.rs
storage-proofs/src/circuit/beacon_post.rs
storage-proofs/src/circuit/drgporep.rs
storage-proofs/src/circuit/pedersen.rs
storage-proofs/src/circuit/por.rs
storage-proofs/src/circuit/porc.rs
storage-proofs/src/circuit/ppor/mod.rs
storage-proofs/src/circuit/vdf_post.rs
storage-proofs/src/circuit/zigzag.rs
storage-proofs/src/crypto/pedersen.rs
storage-proofs/src/example_helper.rs
storage-proofs/src/piece_inclusion_proof.rs
storage-proofs/src/settings.rs

- loads a new setting in from the environment or configuration
- uses the new window size setting when instantiating `JubjubBls12` 
resolves https://github.com/filecoin-project/rust-fil-proofs/issues/736

pass configurable window_size to jubjub

---

.circleci/config.yml

Fixes #786 
We want to capture ZigZag and micro benchmarks for each SHA committed to `master`.
This changeset [adds a new job which runs ZigZag and micro benchmarks](https://circleci.com/gh/filecoin-project/rust-fil-proofs/24885) on the Packet box. Environment variables are set through CircleCI configuration UI, and SSH keys are added in this way, too.

feat(capture benchmarks on pushes to master)

---

.circleci/config.yml

@dignifiedquire recently added a new benchmark to `benchy`, and that benchmark should be run on each `master` build.
This PR runs the `hash-circuits` benchmark on each build of `master.

feat(master builds should capture hash-circuits benchmarks)

---

.circleci/config.yml
fil-proofs-tooling/scripts/benchy.sh
fil-proofs-tooling/scripts/micro.sh

If and when the remote benchmarking fails, we need a way to inspect the state of the system in order to characterize the failure.
This PR prints as much debug output to CircleCI stdout (or whomever runs the remote debug script) as possible.
An example:
```
*********************************************
* benchy failed - dumping debug information *
*********************************************
<COMMAND>
gtime -f '{ "outputs": { "max-resident-set-size-kb": %M } }' cargo run --quiet --bin benchy --release -- hash-constraints > /var/folders/8h/gmmbhq1s5tb8sk9011sy2wkw0000gn/T/tmp.XuhiQMcK 2> /var/folders/8h/gmmbhq1s5tb8sk9011sy2wkw0000gn/T/tmp.OxwswshO
</COMMAND>
<GTIME_STDERR>
error: The subcommand 'hash-constraints' wasn't recognized
Did you mean 'hash-circuits'?
If you believe you received …
```

better remote benchmarking debug-output

---

filecoin-proofs/src/bin/paramfetch.rs
filecoin-proofs/src/param.rs
filecoin-proofs/tests/paramfetch/prompts_to_fetch.rs
filecoin-proofs/tests/paramfetch/support/session.rs

- puts the raw `parameters.json` file as a string into the paramfetch binary
- in https://github.com/filecoin-project/rust-fil-sector-builder/issues/12, `cargo install` would be the simplest way to include `rfp` binaries in with a `rfsb` release, but `parameters.json` is not part of the files downloaded. by including it by default in `paramfetch`, we don't need to worry about packaging anything other than binaries

embed parameters.json in paramfetch binary

---

Dockerfile-profile
README.md

We need to provide an _easy_ setup to profile CPU (and memory, if needed) usage.

feat(profile): add Dockerfile to profile CPU of zigzag example

---

filecoin-proofs/Cargo.toml
filecoin-proofs/src/bin/paramfetch.rs
filecoin-proofs/tests/paramfetch/support/session.rs

This downloads and uses `igpet` to download params, instead of going through the gateway, which has been pretty flaky for us. 
We loose progress bars, as `ipget` doesn't support this atm.

feat(filecoin-proofs): Use ipget to download params

---

filecoin-proofs/src/bin/paramfetch.rs

Fixes #818 
- allow for specific ipget version
- allow for passthrough of arguments of ipget
This is in anticipation of using the new ipget https://github.com/ipfs/ipget/pull/59

Paramfetch flex

---

storage-proofs/Cargo.toml
storage-proofs/src/drgraph.rs
storage-proofs/src/layered_drgporep.rs
storage-proofs/src/merkle.rs

Use new `DiskStore` from https://github.com/filecoin-project/merkle_light/pull/27 instead of the file-`mmap` version, remove the `try_offload` logic since we work _always_ on offloaded (disk-only) stores now (when the `disk-trees` feature is set).
```
cargo build                                                                   \
-p filecoin-proofs                                                          \
--release                                                                   \
--example zigzag                                                            \
--features                                                                  \
disk-trees                                                               &&
export TREES_DIR=rust-fil-proofs-trees-dir                                   && …
```

Disk-only MT

---

fil-proofs-tooling/src/bin/benchy/hash_fns.rs
storage-proofs/benches/pedersen.rs
storage-proofs/src/circuit/drgporep.rs
storage-proofs/src/circuit/pedersen.rs
storage-proofs/src/circuit/por.rs
storage-proofs/src/circuit/porc.rs
storage-proofs/src/circuit/vdf_post.rs
storage-proofs/src/circuit/zigzag.rs
storage-proofs/src/crypto/pedersen.rs
storage-proofs/src/hasher/blake2s.rs
storage-proofs/src/hasher/pedersen.rs
storage-proofs/src/hasher/types.rs
storage-proofs/src/test_helper.rs

Investigating how to make this work, to avoid explosion in constraints
Issues solved:
- use `UInt8` instead of `Boolean` to avoid double constraints for conversions
- use appropriate pedersen window size, to avoid padding
- use bigendian for some encodings as that is what zexe uses

[zexe] refactor: use bytes instead of bits for hashing in and outputs

---

README.md
storage-proofs/Cargo.toml
storage-proofs/src/drgraph.rs
storage-proofs/src/layered_drgporep.rs

To avoid managing them for now. Towards making disk-MTs the default (#831).
This removes the `FIL_PROOFS_REPLICATED_TREES_DIR` option (updated documentation).
Blockers:
--------------------------------------------------
Benchmark:
```
cargo build                                                                   \
-p filecoin-proofs                                                          \
--release                                                                   \
--example zigzag                                                            \
--features                                                                  \
disk-trees                                                               &&
RUST_BACKTRACE=1                                                              \ …
```

fix(storage-proofs): always use temporary files for MTs

---

filecoin-proofs/src/api.rs
storage-proofs/src/circuit/rational_post.rs
storage-proofs/src/lib.rs
storage-proofs/src/rational_post.rs
storage-proofs/src/sector_id.rs

`u64` doesn't tell us much about what values of this type represent (in our domain).
This changeset uses [the newtype pattern](https://doc.rust-lang.org/1.0.0/style/features/types/newtype.html) to wrap `u64` up into a `SectorId` type.

feat(add SectorId type and transforms)

---

.circleci/config.yml
filecoin-proofs/Cargo.toml
filecoin-proofs/parameters.json
filecoin-proofs/src/constants.rs

I cut a release branch last week in which we decreased POST_SECTORS_COUNT from 512 to 4 and modified the parameters manifest to point at the new Groth parameters. We need to backport those changes into rust-fil-proofs master.

backport hotfix branch into master

---

filecoin-proofs/src/api/mod.rs
storage-proofs/src/sector.rs

The Rational PoSt changeset moved us from representing sector id as a 31-byte array (at the API boundary) to a unsigned, 64-bit integer. We forgot to update one of the functions to conform to this new convention.

bug(use SectorId type in API instead of 31-byte array)

---

fil-proofs-tooling/scripts/retry.sh
fil-proofs-tooling/scripts/with-lock.sh

@sidke noticed that I had incorrect sent stderr to stdout. This PR fixes that.

wrap err log-command in parens to ensure echo goes to stderr and not stdout

---

README.md
storage-proofs/Cargo.toml
storage-proofs/src/drgraph.rs
storage-proofs/src/hasher/pedersen.rs
storage-proofs/src/hasher/sha256.rs
storage-proofs/src/layered_drgporep.rs
storage-proofs/src/merkle.rs
storage-proofs/src/settings.rs

Towards making disk-MTs default (https://github.com/filecoin-project/rust-fil-proofs/issues/831), a suboptimal solution to https://github.com/filecoin-project/rust-fil-proofs/issues/826. (Using new features from MT repo in https://github.com/filecoin-project/merkle_light/pull/31).
-------------------------------------------
For speed we both build MT and encode in parallel, the price to pay in an entire sector size duplication to decouple the two process so the modification of the encoding of the new layer doesn't affect the MT being build off the current one. For memory we do both processes sequentially, so we don't need the extra allocation to decouple them, greatly slowing down replication as a whole.
In the middle of these two extremes there seems to be an acceptable scenario that …

Remove extra `data` allocation used for MT generation

---

.circleci/config.yml
fil-proofs-tooling/src/bin/benchy/main.rs
fil-proofs-tooling/src/bin/benchy/zigzag.rs
filecoin-proofs/examples/drgporep-vanilla-disk.rs
filecoin-proofs/examples/drgporep-vanilla.rs
filecoin-proofs/examples/encoding.rs
filecoin-proofs/examples/zigzag.rs
filecoin-proofs/src/parameters.rs
storage-proofs/Cargo.toml
storage-proofs/benches/drgraph.rs
storage-proofs/benches/merkle.rs
storage-proofs/benches/parents.rs
storage-proofs/src/circuit/drgporep.rs
storage-proofs/src/circuit/por.rs
storage-proofs/src/circuit/porc.rs
storage-proofs/src/circuit/ppor/mod.rs
storage-proofs/src/circuit/zigzag.rs
storage-proofs/src/drgporep.rs
storage-proofs/src/drgraph.rs
storage-proofs/src/merkle.rs
storage-proofs/src/merklepor.rs
storage-proofs/src/piece_inclusion_proof.rs
storage-proofs/src/porc.rs
storage-proofs/src/zigzag_drgporep.rs
storage-proofs/src/zigzag_graph.rs

This is the first step to pulling in optimizations from r2. 
Important changes:
- All graphs are now using the degrees 5 + 8, including all tests and exposed sector sizes.
- degrees are no inputs anymore for the circuits, need to validate this is okay
- This will require new params
- Adds compile-time feature `allow-small-degree` which allows graphs to be constructed with base and expansion degrees smaller than 5 and 8 respectively. This feature is enabled in the CI for the ignored `storage-proofs` tests.

refactor(storage-proofs): make base and expansion parents compile time constants

---

fil-proofs-tooling/src/metadata.rs
storage-proofs/src/zigzag_graph.rs

Switches the cache structure to something towards what is described in #847. This still keeps everything in memory though. 
This also removes the cloning of the cache, when cloning the graph.
For 128MiB sectors the following memory usage changes can be seen 
**with `disk-trees`**
| state  | max res memory   |
|--------|------------------|
| master |  1_714_648 bytes |
| 02718b6 | 1_285_292 bytes |
| beeee94  | 1_285_232 bytes |
**without `disk-trees`**
| state  | max res memory   |
|--------|------------------|
| master  | 4_532_592 bytes |
| 02718b6 | 4_167_780 bytes |
| beeee94  | 4_068_068 bytes |

refactor(storage-proofs): streamline expander parents cache

---

.circleci/config.yml
README.md
storage-proofs/Cargo.toml
storage-proofs/src/merkle.rs

Alternatively we could invert the feature and have a `ram-trees`/`mem-trees` feature.
Closes https://github.com/filecoin-project/rust-fil-proofs/issues/831.
-------------------------------
Benchmark:
```
RUSTFLAGS="-C target-cpu=native" cargo build --bin benchy --release
RUST_LOG=info /usr/bin/time -v ./target/release/benchy zigzag --size 262144
```
```
MASTER (disk-trees *not* set):
User time (seconds): 10724.92
System time (seconds): 12.24
Percent of CPU this job got: 643%
Elapsed (wall clock) time (h:mm:ss or m:ss): 27:48.98
Maximum resident set size (kbytes): 6693416
PR (disk-trees set as default):
User time (seconds): 10712.94
System time (seconds): 20.55
Percent of CPU this job got: 648%
Elapsed (wall clock) time (h:mm:ss or m:ss): 27:34.49
Maximum resident set size (kbytes): 926748 …
```

feat(storage-proofs): use disk-trees feature as default

---

.circleci/config.yml
fil-proofs-tooling/Cargo.toml
fil-proofs-tooling/scripts/aggregate-benchmarks.sh
fil-proofs-tooling/src/bin/benchy/main.rs
fil-proofs-tooling/src/bin/benchy/rational_post.rs
fil-proofs-tooling/src/bin/benchy/zigzag.rs
fil-proofs-tooling/src/lib.rs
fil-proofs-tooling/src/measure.rs

Adds `rational-post` subcommand to `benchy` for benchmarking `generate_post()` and `verify_post()`.
Closes #846

feat(fil-proofs-tooling): add rational-post subcommand to benchy

---

filecoin-proofs/parameters.json
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/bin/paramcache.rs
filecoin-proofs/src/bin/paramgen.rs
filecoin-proofs/src/constants.rs

Fixes #625 
The go-lotus team wants 16MiB sectors and the go-filecoin team wants 1GiB sectors.
This changeset modifies paramcache to generate Groth parameters and verifying keys for 16MiB  and 1GiB sectors alike. It also updates the parameters.json file.

publish 1GiB and 16MiB sector sizes

---

filecoin-proofs/src/bin/parampublish.rs
storage-proofs/src/parameter_cache.rs

feat(env): rename parameter cache environment variable to convention

---

storage-proofs/src/layered_drgporep.rs

I tracked down the source of confusion noted here: https://github.com/filecoin-project/rust-fil-proofs/pull/895/files/3ad6277a438e13c0c64d141ebbad9c0cb45bd78b#r332336497

Clarify conditions around use of LayeredDrgPoRep::prove.

---

fil-proofs-tooling/src/bin/benchy/rational_post.rs
filecoin-proofs/src/api/mod.rs
storage-proofs/src/stacked/params.rs

- prover_id is now a [u8; 32]
- sector_id gets properly hashed as [u8; 8] not [u8; 32]
- use blake2s to calculate the replica_id

feat: normalize ids

---

.circleci/config.yml

The existing metrics capture CircleCI config is busted, which means that `master` is busted.
This PR fixes the CircleCI config such that metrics can again be captured.

fix(benchmarks): fix benchmark invocations

---

fil-proofs-tooling/src/bin/benchy/rational_post.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/post.rs

The `seal` function creates a bunch of merkle trees which `generate_post` needs to make use of (so that it doesn't have to regenerate said merkle trees).
This PR modifies both `seal` and `generate_post` to accept a per-sector cache path. The `seal` function will ultimately write to this directory and `generate_post` will read from it.

feat(filecoin-proofs): generate_post and seal both accept cache dir-path

---

fil-proofs-tooling/scripts/benchy.sh
fil-proofs-tooling/scripts/micro.sh
fil-proofs-tooling/src/bin/benchy/rational_post.rs

Ensure that:
- len(user bytes) < len(bit-padded(user bytes))
- we pass the correct file to pre_commit
- we propagate failures encountered when running benchy

fix(benchy): pass correct file path to pre_commit + create correctly-sized byte vector

---

filecoin-proofs/src/api/seal.rs

The `seal_pre_commit` function expects that the sealed sector file exists before replicating. Without this changeset, passing a path to a file which doesn't exist results in an unhelpfus "Os: Not Found" error message.

feat(errors): produce a nice error message if files don't exist

---

filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/seal.rs
filecoin-proofs/src/pieces.rs

This addresses an inconsistency in the API:
- `verify_seal` was taking both `comm_d` and `[]PieceInfo` — only one should be required.
- Add an API function `compute_comm_d` which allows caller to get the `comm_d` corresponding to an array of `PieceInfo`s.
It is an error if the provided`PieceInfo`s cannot be used to create a valid `comm_d` for sectors using the provided config. In the future, the requirements on allowable pieces will grow to include a maximum allowable padding, and this function will need to enforce that check.

Add compute_comm_d to API.

---

filecoin-proofs/Cargo.toml
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/pieces.rs

The verify_seal function will soon reject sectors which were not packed up to some threshold. Also, generating the CommP can happen in a streaming fashion (by miners) at the time of writing and preprocessing.
1. Exposes new vanity function which never adds alignment bytes
1. Modifies piece-adding functions to produce piece commitment in addition to number of bytes written-value

expose piece-writing function which expects caller to bin pack

---

filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/pieces.rs

If a piece is not sized correctly, our system produces an error when we try to add it to a staged sector. This error now includes the size of the piece to be added, which helps in debugging. We also alert the user to an EOF from the byte source, which is typically caused when caller passes a fd that needs to be fseeked back to its head.

refactor(filecoin-proofs): add more information to piece size errors

---

storage-proofs/src/circuit/create_label.rs
storage-proofs/src/circuit/drgporep.rs
storage-proofs/src/circuit/mod.rs
storage-proofs/src/circuit/stacked/encoding_proof.rs
storage-proofs/src/circuit/stacked/labeling_proof.rs
storage-proofs/src/circuit/stacked/mod.rs
storage-proofs/src/circuit/stacked/params.rs
storage-proofs/src/circuit/stacked/proof.rs
storage-proofs/src/crypto/create_label.rs
storage-proofs/src/crypto/mod.rs
storage-proofs/src/hasher/blake2s.rs
storage-proofs/src/hasher/pedersen.rs
storage-proofs/src/hasher/sha256.rs
storage-proofs/src/hasher/types.rs
storage-proofs/src/stacked/challenges.rs
storage-proofs/src/stacked/column_proof.rs
storage-proofs/src/stacked/encoding_proof.rs
storage-proofs/src/stacked/labeling_proof.rs
storage-proofs/src/stacked/mod.rs
storage-proofs/src/stacked/params.rs
storage-proofs/src/stacked/proof.rs
storage-proofs/src/stacked/proof_scheme.rs
storage-proofs/src/test_helper.rs

The first round of updating naming and adjusting some smaller things better matching the spec.
Important to note
- fixed logic in tapering, such that it starts at the last layer note the first
- split labeling proofs and encoding proofs
- add missing round of labeling proofs for the last layer

fix(storage-proofs): spec sync 

---

.circleci/config.yml
fil-proofs-tooling/scripts/paramcache-remote.sh

The metrics_capture job relies on the existence of Groth parameters and keys for PoSt generation and sealing. Without this PR, new parameters will be generated lazily, impacting performance metrics.
- delete cache restoration steps from metrics_capture
- invoke paramcache on remote host to ensure params n' keys

fix(params): ensure benchmarking server has groth params and keys before running benchmarks

---

fil-proofs-tooling/src/bin/benchy/election_post.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/post.rs
storage-proofs/src/election_post.rs

The number of challenges for a given miner is a function of the size of their proving set - but we don't know what that function is. It may be a per-miner value or it may be a network-wide parameter. Either way, it's in a state of flux. 
This changeset allows the caller of the rust-fil-proofs library to provide a challenge count instead of having the rust-fil-proofs library do this for them.

caller to provide challenge count to PoSt ops

---

filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/seal.rs
filecoin-proofs/src/bin/paramcache.rs
filecoin-proofs/src/caches.rs
filecoin-proofs/src/parameters.rs
filecoin-proofs/src/types/porep_config.rs
filecoin-proofs/src/types/post_config.rs
storage-proofs/benches/encode.rs
storage-proofs/src/circuit/create_label.rs
storage-proofs/src/circuit/variables.rs
storage-proofs/src/crypto/create_label.rs
storage-proofs/src/drgporep.rs
storage-proofs/src/hasher/blake2s.rs
storage-proofs/src/hasher/pedersen.rs
storage-proofs/src/hasher/sha256.rs
storage-proofs/src/hasher/types.rs
storage-proofs/src/stacked/params.rs
storage-proofs/src/stacked/proof.rs
storage-proofs/src/test_helper.rs

This is the first step to having less panics. I went through all the `unwrap()`s in the code and removed most of then (except the ones in tests and binaries). There is still a few unwraps left. Some are safe (when there are prior assertions about them) or where it is logically safe (like allocating a 32 byte array and writing 32 bytes into it.
There are still a few `unwrap()`s left with a todo. Those are the ones within a parallel iterator that is using `flat_map()`. Handling errors there is not that simple and needs more thought.
Please also note that this PR is only about `unwrap()`s. There is still other cases where panics could be triggered (e.g. by `assert!()`s) Those other cases will be fixed by subsequent PRs.
Please do a thorough review, some changes are non-trivial and perhaps …

Reduce unwrap()s in code

---

.circleci/config.yml

- jobs which run tests now need to populate their Groth parameter cache
- stop publishing build artifacts (paramcache and paramfetch and parameters.json)
- make sure we run the test suite with Darwin and not just Linux
- general refactor of CircleCI config

rework CircleCI config

---

fil-proofs-tooling/src/bin/benchy/election_post.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/post.rs
filecoin-proofs/src/api/seal.rs
filecoin-proofs/src/pieces.rs
filecoin-proofs/src/types/piece_info.rs

This is about commitments in `filecoin-proofs`.  `storage-proofs` seem to use another type of commitments.

fix: add more sanity checks for commitments

---

fil-proofs-tooling/scripts/benchy-remote.sh
fil-proofs-tooling/scripts/micro-remote.sh

The existing remote benchmarking code doesn't clean up the temp directory (in which it builds rust-fil-proofs), causing the host to run out of disk after a few days.
This changeset removes the temporary directory after the benchmark completes.

fix(benchmarking): clean temp directory on exit

---

filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/post.rs
filecoin-proofs/src/api/seal.rs
filecoin-proofs/src/param.rs

IO errors do not contain much context about which file failed. Giving
this context should make debugging easier.

fix: better IO errors

---

fil-proofs-tooling/Cargo.toml

Without using heim version 0.0.9 explicitly, version 0.0.7 will be used implicitly,
which results in a broken build.
The error message prior to this fix is:
```
Compiling fil-proofs-tooling v0.6.1 (/tmp/rust-fil-proofs/fil-proofs-tooling)
error[E0277]: the trait bound `uom::si::information::byte: uom::si::information::Unit` is not satisfied
--> fil-proofs-tooling/src/metadata.rs:110:48
|
110 |             memory_total_bytes: memory.total().get::<uom::si::information::byte>(),
|                                                ^^^ the trait `uom::si::information::Unit` is not implemented for `uom::si::information::byte`
error[E0277]: the trait bound `uom::si::information::byte: uom::Conversion<u64>` is not satisfied
--> fil-proofs-tooling/src/metadata.rs:110:48
|
110 | …
```

fix: uom 0.26 needs at least heim 0.0.9

---

fil-proofs-tooling/Cargo.toml
filecoin-proofs/Cargo.toml
filecoin-proofs/src/api/post.rs
filecoin-proofs/src/api/seal.rs
filecoin-proofs/src/pieces.rs
filecoin-proofs/src/types/mod.rs
storage-proofs/Cargo.toml
storage-proofs/benches/merkle.rs
storage-proofs/src/circuit/drgporep.rs
storage-proofs/src/circuit/election_post.rs
storage-proofs/src/circuit/por.rs
storage-proofs/src/circuit/rational_post.rs
storage-proofs/src/drgporep.rs
storage-proofs/src/drgraph.rs
storage-proofs/src/election_post.rs
storage-proofs/src/merkle.rs
storage-proofs/src/merklepor.rs
storage-proofs/src/parameter_cache.rs
storage-proofs/src/porep.rs
storage-proofs/src/rational_post.rs
storage-proofs/src/stacked/params.rs

~~Happens to be built on top of the mmap params branch~~, but in any case, it's a start of the LevelCacheStore integration where we can compact `tree_r_last` and generate the proofs using partially built trees.

feat: use LevelCacheStore for restoring tree_r_last from disk

---

.circleci/config.yml
filecoin-proofs/src/api/post.rs
filecoin-proofs/src/api/util.rs
storage-proofs/Cargo.toml
storage-proofs/src/circuit/election_post.rs
storage-proofs/src/circuit/mod.rs
storage-proofs/src/election_post.rs
storage-proofs/src/hasher/poseidon.rs
storage-proofs/src/hasher/types.rs
storage-proofs/src/sector.rs

Add just enough support for Merkle-Damgard construction to use with Poseidon.
- Add `hash_md` and `hash_md_circuit` methods to `HashFunction` trait.
- Default `hash_md` implementation in terms of `hash2` (untested).
- No default implementation for `hash_md_circuit`.
- Implement both for `PoseidonDomain`.
- Use arity 36 by default.
- NOTE: Arity is a program-wide constant, 'PoseidonMDArity`.

feat: add md hash and implement for Poseidon

---

storage-proofs/Cargo.toml

More information:
https://users.rust-lang.org/t/failure-derive-compilation-error/39062

fix: lock 'quote' dependency to fix failure-derive

---

filecoin-proofs/src/lib.rs

Make pub so we can use it outside.
Additional request: can we change the name of this to `fr32_pad_reader::Fr32PadReader`? We've got naming confusion with the base2 size padding that's done prior to hand-off to `generate_piece_commitment()`, which now even has its own repo: https://github.com/filecoin-project/go-padreader (also of note is that this new repo's README talks as if it's bit padding and not zero-byte extended padding so confusion already abounds). It comes out of Lotus https://github.com/filecoin-project/lotus/blob/a1f676bf3047646750aa394281a328decd0dd7c4/lib/padreader/padreader.go, made its way to go-fil-markets and is now in its own repo. I'm also having to rename my Rust "PadReader" @ https://github.com/rvagg/rust-fil-commp-generate/blob/edb2a8a837d344bf2ae0eff4384e0fb82c3b6 …

feat(filecoin-proofs): expose filecoin_proofs::pad_reader

---

filecoin-proofs/benches/preprocessing.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/commitment_reader.rs
filecoin-proofs/src/fr32.rs
filecoin-proofs/src/fr32_reader.rs
filecoin-proofs/src/lib.rs
filecoin-proofs/src/pieces.rs

For clarity, since padding input data to achieve correct ^2 output size prior to CommP calculation is also required.
Ref #1061 
tbh I've been messing with and around Fr32 padding for a couple of months now but I still don't know what it stands for, is it an acronym? Therefore, I don't know for sure that using the name "Fr32Reader" makes as much sense as it could.
Is this "feat", "fix", "chore", or something else? It's a breaking change but it was only exposed publicly a couple of days ago so maybe a "fix"?

refactor(filecoin-proofs): pad_reader::PadReader fr32_reader::Fr32Reader

---

filecoin-proofs/Cargo.toml
filecoin-proofs/src/fr32.rs
filecoin-proofs/src/fr32_reader.rs
storage-proofs/Cargo.toml
storage-proofs/src/crypto/pedersen.rs

The old versions were yanked due to a unsafety issue

fix: update bitvec to 0.17

---

.circleci/config.yml

fixes errors in CircleCI mac builds, such as
```
---- fallback::vanilla::tests::fallback_post_poseidon_two_partitions_smaller_top_8_8_2 stdout ----
thread 'fallback::vanilla::tests::fallback_post_poseidon_two_partitions_smaller_top_8_8_2' panicked at 'called `Result::unwrap()` on an `Err` value: Too many open files (os error 24)', /Users/distiller/crate/storage-proofs/core/src/merkle/builders.rs:411:13
```
Fix sets ulimit for system, users (`sudo ulimit` calls) and then user sets ulimit (without `sudo`)

ci: fix file descriptor limits on macOS

---

filecoin-proofs/Cargo.toml
filecoin-proofs/src/bin/parampublish.rs
filecoin-proofs/src/bin/phase2.rs
filecoin-proofs/src/param.rs
filecoin-proofs/tests/parampublish/prompts_to_publish.rs
filecoin-proofs/tests/parampublish/read_metadata_files.rs
filecoin-proofs/tests/parampublish/write_json_manifest.rs

This PR fixes parts of https://github.com/filecoin-project/rust-fil-proofs/issues/1079.
I originally misunderstood some of the requirements, hence it got fancier then probably anticipated. You can now select the sizes you want to publish, with having the defaults pre-selected.
This PR can also be reviewed commit per commit, I tried to make them self-contained (the commit message should explain some of the reasons for some of the changes).
@DrPeterVanNostrand I've added you for review as I updated dialoguer, which also needed a little change in the phase2 bin code. I just want to make sure you are aware of that change, in case something breaks (which I won't expect).
This PR supersedes #1090.

feat(filecoin-proofs): improve parampublish

---

.circleci/config.yml
filecoin-proofs/src/constants.rs

PoRep Constraints for 32Gib are down to 999,619,996.

feat(filecoin-proofs): reduce porep partitions to 8

---

fil-proofs-tooling/src/bin/benchy/main.rs
fil-proofs-tooling/src/bin/benchy/prodbench.rs
fil-proofs-tooling/src/bin/benchy/shared.rs
fil-proofs-tooling/src/bin/benchy/window_post.rs
fil-proofs-tooling/src/bin/benchy/winning_post.rs
fil-proofs-tooling/src/lib.rs
fil-proofs-tooling/src/shared.rs

In the fil-proofs-tooling it's a common operation to create replicas. This creation is now properly refactored so that it can be used by several binaries.
This commit doesn't change any functionality it's a pure refactoring.
The commits are self-contained so this PR might be easier to review on a commit per commit basis.

tooling: refactor create_replicas()

---

filecoin-proofs/Cargo.toml
filecoin-proofs/src/bin/paramcache.rs

When no sizes are given as input, you get a multiselect dialog on
the terminal.
Also the parameter generation now has a spinning indicator while
parameters are generated.

fix: improve paramcache

---

storage-proofs/core/src/test_helper.rs
storage-proofs/porep/src/drg/circuit.rs
storage-proofs/porep/src/drg/compound.rs
storage-proofs/porep/src/drg/vanilla.rs
storage-proofs/porep/src/stacked/circuit/params.rs
storage-proofs/porep/src/stacked/circuit/proof.rs
storage-proofs/porep/src/stacked/vanilla/proof.rs

fix: clean-up unrelated clippy warnings

fix: avoid extra replica disk write where not required

---

.circleci/config.yml

This PR attempts to fix the broken CI metrics-update

fix: replace (broken) metrics capture of election with window-post

---

filecoin-proofs/src/api/mod.rs
filecoin-proofs/tests/api.rs
storage-proofs/core/benches/pedersen.rs

@magik6k has indicated that he'd like to be able to unseal a sector to a file descriptor. While both file descriptors and regular files have paths, the more ergonomic way to do this is to use `Read` and `Write` instead of concrete types.
This PR introduces a new function, `unseal_range`, which reads bytes from a `Read` and writes output to a `Write`. It then implements `get_unsealed_range` in terms of `unseal_range`.

unseal using Read and Write instead of Path or PathBuf

---

.circleci/config.yml
fil-proofs-tooling/Cargo.toml
filecoin-proofs/Cargo.toml
storage-proofs/core/src/gadgets/insertion.rs
storage-proofs/core/src/gadgets/por.rs
storage-proofs/core/src/lib.rs
storage-proofs/core/src/parameter_cache.rs
storage-proofs/porep/src/stacked/circuit/proof.rs
storage-proofs/post/src/election/circuit.rs
storage-proofs/post/src/fallback/circuit.rs

This PR updates `insertion.rs` to use hand-optimized versions of insertion when the size of the output array is either 4 or 8. These are the sizes used for our merkle trees and for which optimization will help. By taking advantage of redundancy in the output for each position, we can avoid the full generality otherwise required. This allows us to avoid the quadratic cost of `size * (size - 1)` constraints.
In order to aid in legibility and for consistency with internal spec audit (the motivation for this change), I have introduced a macro, `witness!` which allows declarative assignment of constraints to allocated numbers based on the value of an allocated boolean value.
Previous behavior is preserved and verified in tests — so bit input for insertion is still little endian. Bit and …

optimize oct and quad insertion

---

storage-proofs/core/Cargo.toml

Currently the build fails when run with
cargo build --all-features
This is because of a missing optional dependencie on `gperftools`.
Add the dependency as an optional dev dependency for the `measurements` feature on `core` crate.
Found while working on: https://github.com/filecoin-project/rust-fil-proofs/issues/1123

build(storage-proofs): fix build for profile feature

---

storage-proofs/core/src/merkle/tree.rs
storage-proofs/porep/src/stacked/vanilla/proof.rs

We have a few places where the `assert!` macro is used with a comment
```
// For development and debugging.
```
We have a macro for development and debugging, its `debug_assert!`.
Use `debug_assert` and remove the now redundant comment.

refactor(storage-proofs): use debug_assert

---

.circleci/config.yml
storage-proofs/.gitignore
storage-proofs/core/src/gadgets/por.rs
storage-proofs/porep/benches/encode.rs
storage-proofs/porep/src/stacked/circuit/create_label.rs
storage-proofs/porep/src/stacked/circuit/params.rs
storage-proofs/porep/src/stacked/circuit/proof.rs
storage-proofs/porep/src/stacked/vanilla/create_label.rs
storage-proofs/porep/src/stacked/vanilla/encoding_proof.rs
storage-proofs/porep/src/stacked/vanilla/labeling_proof.rs
storage-proofs/porep/src/stacked/vanilla/proof.rs

This adds constraints, which slightly surprised me — since it does not increase the length of the preimage being hashed. ~I believe the reason for this is that the padding bits being replaced were in fact boolean constants. Some initial operations in the sha256 computation involving them may therefore have been optimized away at synthesis time.~
*UPDATE:* I don't think my explanation above makes sense. I think the actual source of the increase is the booleanity constraints introduced when allocating the bits.
*UPDATE 2*: Although my update is accurate, there should not have been an allocation. The latest should now correctly use constants everywhere.

Include layer index before node when creating label preimage.

---

storage-proofs/porep/src/stacked/vanilla/challenges.rs

A comment in the challenge-derivation code suggested that we cannot challenge either the first or the last node (of each layer). This was true of ZigZag but does not hold with SDR. The underlying code, however, only excludes the first node (index 0) of each layer.
This PR corrects the comment.
It also incidentally uncomments a test which had been commented with a note to investigate why it now fails. This test represents a simple sanity check to ensure our challenge-generation method is not systematically producing an unexpectedly high number of duplicates. If it does begin to fail regularly, that *is* cause for investigation.

Fix misleading comment and restore test.

---

.circleci/config.yml
storage-proofs/core/src/util.rs
storage-proofs/porep/src/drg/circuit.rs
storage-proofs/porep/src/stacked/circuit/create_label.rs
storage-proofs/porep/src/stacked/circuit/params.rs
storage-proofs/porep/src/stacked/circuit/proof.rs

When creating a label, the bits resulting from the SHA256 circuit were not being constrained to the returned result — although that result was correctly computed. This PR corrects that.
- Use `pack_bits` instead of `compute_multipacking`. This adds one constraint per call to `create_label`.
- Use a general utility function (`reverse_bit_numbering` was `fixup_bits`) rather than ad-hoc transformation of the sha256-result bit array.
- Rename `fixup_bits`, an inscrutable and domain-specific name, to the transparent and general-purpose `reverse_bit_numbering`. NOTE: I chose 'bit numbering' (https://en.wikipedia.org/wiki/Bit_numbering) rather than 'bit endianness' to avoid potential ambiguity when mentioning 'endianness', since this function preserves byte order (when the bit array is viewed as …

Constrain bits to result when creating label.

---

storage-proofs/core/src/drgraph.rs
storage-proofs/porep/benches/encode.rs
storage-proofs/porep/src/drg/vanilla.rs
storage-proofs/porep/src/stacked/vanilla/graph.rs

This PR is a follow-up to #1144. It removes the old `FEISTEL_KEYS` constant and instead uses the keys created from the `porep_id`.

fix: finish propagating porep_id.

---

filecoin-proofs/src/bin/paramcache.rs

Make clear that you should use the space key to select items.
I just started it myself and was confused that I got an error that no parameters were selected.

fix: better paramcache UX

---

filecoin-proofs/src/constants.rs

Since the actual values were not updated, the lines of code bearing concrete constraint counts for Window PoSt escaped the release without being updated. This PR fixes that.

Updated reported Window PoSt constraints (in comments).

---

fil-proofs-tooling/src/bin/benchy/main.rs
fil-proofs-tooling/src/bin/benchy/window_post.rs
filecoin-proofs/src/types/mod.rs
filecoin-proofs/src/types/piece_info.rs

This work allows a cached directory to be preserved across runs so
that precommit_phase1, precommit_phase2, commit_phase1, and
commit_phase2 can be run in any combination for specific phase testing
(or isolating window post generation).  For now, precommit phase1/2
are controlled by a single option.

feat: modularize window post bench

---

fil-proofs-tooling/src/bin/benchy/stacked.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/post.rs
filecoin-proofs/src/api/seal.rs
storage-proofs/core/src/merkle/builders.rs
storage-proofs/core/src/settings.rs
storage-proofs/core/src/util.rs
storage-proofs/porep/src/drg/circuit.rs
storage-proofs/porep/src/drg/compound.rs
storage-proofs/porep/src/drg/vanilla.rs
storage-proofs/porep/src/stacked/circuit/proof.rs
storage-proofs/porep/src/stacked/vanilla/proof.rs

feat: move default value from merkle_light to internal

fix: change default rows_to_discard for oct trees

---

fil-proofs-tooling/Cargo.toml
fil-proofs-tooling/src/bin/update_tree_r_cache/main.rs
storage-proofs/core/src/merkle/tree.rs

This PR adds a tool for rebuilding tree_r_last trees from a replica file.  The intended usage is for replacing existing trees with an updated `rows_to_discard` setting, as trees with different values for that setting are incompatible.
OPTIONAL (one time sanity check, but can be skipped entirely): To verify that the tool works as expected, let's use the 'old' default of rows_to_discard as 3 for 32GiB sectors and simply rebuild them to make sure the data produced exactly matches what's already present:
```
time RUST_LOG=trace RUSTFLAGS="-C target-cpu=native" FIL_PROOFS_ROWS_TO_DISCARD=3 cargo run --release --bin update_tree_r_cache rebuild --size 34359738368 --cache /some/new/output/dir --replica /path/to/existing/sealed-file
```
OPTIONAL (continued): After this completes, use md5sum to …

feat: rebuild tree_r_last trees from a replica file

---

fil-proofs-tooling/src/bin/benchy/stacked.rs
filecoin-proofs/src/api/seal.rs
storage-proofs/core/src/drgraph.rs
storage-proofs/core/src/proof.rs
storage-proofs/porep/src/stacked/circuit/proof.rs
storage-proofs/porep/src/stacked/vanilla/graph.rs
storage-proofs/porep/src/stacked/vanilla/params.rs
storage-proofs/porep/src/stacked/vanilla/proof.rs
storage-proofs/porep/src/stacked/vanilla/proof_scheme.rs

Use of `porep_id` in generating `replica_id`, when deriving drg seed, and when deriving feistel keys are independent. This PR adds a check to ensure they are consistent. Current `filecoin_proofs` API function will always pass the correct `porep_id` obtained from the `PoRepConfig` and therefore be 'consistent'. The checks inserted here ensure this is true.
**UPDATE**: In fact, `porep_id` still being a public input was a vestige of its evolution and no longer required. So consistency is produced even more simply by removing it altogether.

fix: verify consistent use of porep_id when sealing

---

fil-proofs-tooling/Cargo.toml
storage-proofs/core/src/parameter_cache.rs
storage-proofs/core/src/settings.rs
storage-proofs/porep/Cargo.toml
storage-proofs/porep/benches/encode.rs
storage-proofs/porep/src/stacked/circuit/create_label.rs
storage-proofs/porep/src/stacked/circuit/proof.rs
storage-proofs/porep/src/stacked/vanilla/cache.rs
storage-proofs/porep/src/stacked/vanilla/create_label.rs
storage-proofs/porep/src/stacked/vanilla/graph.rs
storage-proofs/porep/src/stacked/vanilla/mod.rs
storage-proofs/porep/src/stacked/vanilla/proof.rs

- reduces memory usage during `precommit_phase1` by 56GiB for 3i2GB sectors, when using max caching
- generate and store parents cache on disk
- mmap cache to use it 
- only mmap part of it, to minimize memory usage 
- cache is local, not global anymore
- cache can be used by all sector sizes
- enables cache usage by default, given its small overhead (112 KiB at the current configuration)
- increases required fast disk space by 56GiB for 32GiB sectors, this file is stored in `/var/tmp/filecoin-parents` for now
Based on the ideas in #1135

feat(storage-proofs): partial caching for SDR

---

filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/post.rs
filecoin-proofs/src/api/seal.rs

From the issue description: "FFI exposed functions should log when called and right before they return."
Add logging to all the public functions (excl. public trait implementations) within the `api` module.
This issue (#650) is a bit out of date, I've made the best of what I could understand given the description. If I've missed the mark feel free to say and I can do whatever is needed to fix it up. Thanks.
I elected to use a style with no newline between the final log statement and the return value to help make explicit that the log statement should remain at the end of the function. Also, I made some existing functions more uniform (some had ':end' instead of ':finish' in the log message).
When reviewing, please confirm that this does actually close #650.
Closes: #650

fix(filecoin-proofs): add logging to all public API functions

---

README.md

After cloning the repository `cargo build` fails if the system does not have OpenCL installed.
Add comment as such, including Ubuntu command to install OpenCL.

docs: add OpenCL to the build instructions

---

fil-proofs-tooling/Cargo.toml
fil-proofs-tooling/src/bin/update_tree_r_cache/main.rs
filecoin-proofs/src/constants.rs

Added are 'inspect' and 'verify' options.  Inspect makes sure the cache is consistent with itself and verify rebuilds trees and then verifies against the cached data (which can detect an error in the replica data).

feat: extend update_tree_r_cache command with new features

---

filecoin-proofs/src/constants.rs

The motivation for this is because of a broken test that attempts to use this from rust-filecoin-proofs-api, which always fails due to the parameter file not being available

fix: allow parameters map to be accessible externally

---

README.md
fil-proofs-tooling/Cargo.toml
filecoin-proofs/Cargo.toml
filecoin-proofs/src/bin/paramfetch.rs
filecoin-proofs/src/bin/parampublish.rs
filecoin-proofs/tests/paramfetch/support/session.rs
filecoin-proofs/tests/parampublish/support/session.rs
storage-proofs/core/Cargo.toml
storage-proofs/core/src/parameter_cache.rs
storage-proofs/core/src/settings.rs
storage-proofs/porep/Cargo.toml
storage-proofs/porep/src/stacked/vanilla/cache.rs
storage-proofs/post/Cargo.toml
storage-proofs/post/src/fallback/circuit.rs

feat: add some README notes on available settings

---

fil-proofs-tooling/src/bin/update_tree_r_cache/main.rs
filecoin-proofs/Cargo.toml
filecoin-proofs/src/bin/phase2.rs

This PR adds streaming contribution to phase2 and makes it the default. This caps memory usage. The somewhat arbitrarily chosen batch size seems to keep memory usage around 20MB without a performance penalty.
This PR also add support for 'raw i/o'. This means that the read/write operations in the streaming hot path avoid expensive transformations in and out of montgomery space. This makes contribution ~10x faster.
The expected net result of this PR is that contribution to even our large circuits should be possible in reasonable time and without extremely beefy hardware. (Actual times and RAM usage will need to be measured on real hardware, of course.)
Before (non-streaming non-raw) contribution time: 51.62s
Before mem: 53460992 bytes
After (streaming raw) contribution time:  5.26s
After …

Streaming contribution and fast contribution i/o

---

filecoin-proofs/src/api/seal.rs
filecoin-proofs/tests/api.rs
storage-proofs/porep/src/stacked/vanilla/proof.rs

This PR adds a new API function, `fauxrep`, which allows fake sealing for testing purposes. `fauxrep` takes a `PoRepConfig`, a replica path, and a cache path — and returns a new, random-but-valid `CommR` and writes all artifacts needed to legitimately pass PoSt. No PoRep is performed, and no proof is returned. If `FIL_PROOFS_USE_GPU_TREE_BUILDER` is set, the replica tree will be built on GPU.
All fake replicas consist entirely of null bytes, and the implementation depends on this assumption for simplicity. This means all such replicas have interchangeable base layers, partial trees, and `comm_r_last` values. They differ only in the value of their `comm_c`, which is stored in the `p_aux` file. This value is randomly generated and is the reason fake replicas have unique `comm_r`s.
The PoST …

Add fauxrep to API for fake sealing.

---

filecoin-proofs/src/pieces.rs

The `pieces::Stack` struct is only used in the implementation of `compute_comm_d`, and accurate usage of its helper methods is required for correctness. For example, `peek()` and `peek2` must not be called when the stack is not large enough. This correctness is guaranteed by usage of `Stack` as a helper data structure within `compute_comm_d` as written, but there is no reason to expose these methods to callers who *might* misuse them. Put differently, correctness of the `Stack` data structure depends on these methods being private. This allows a reader to determine — by only inspecting  the `pieces` module — that these methods are never called incorrectly.

Make pieces::Stack methods private.

---

storage-proofs/porep/src/stacked/vanilla/proof.rs

opt: Stacked DRG: swap buffers instead of memcpy #1197

---

storage-proofs/core/src/settings.rs

Closes #1206.
~NOTE: Do not merge until a decision is made. This PR was a proposal for @lanzafame's approval, but merging it may cause as much or more trouble as the originally reported problem.~
UPDATE: We have settled on solution: separate actual cache usage from canonical parameter location.
*In particular, we must ensure the location of the Groth parameter cache does not change for any user.* (cc: @travisperson)
This is untested, but I wanted to push something quickly for @lanzafame to review, since this is high priority for him.
@lanzafame Please approve if this seems to satisfy your requirements. If so, ~we'll~ we might get this into the upcoming release after making sure it's solid.
TODO:

Default cache paths to use FIL_PROOFS_CACHE_DIR if set.

---

.circleci/config.yml
fil-proofs-tooling/scripts/aggregate-benchmarks.sh
fil-proofs-tooling/scripts/run-remote.sh
fil-proofs-tooling/src/bin/benchy/main.rs
fil-proofs-tooling/src/bin/benchy/merkleproofs.rs

feat: enable proof validate by default on merkleproof bench
While proofs_count is CLI configurable, if it's more than the number
of nodes in the tree, just sequentially challenge each node in the
tree instead of randomly selecting and over-proving.

Fix CI metrics_capture

---

filecoin-proofs/src/api/seal.rs
storage-proofs/porep/Cargo.toml
storage-proofs/porep/src/stacked/vanilla/proof.rs

This PR implements `fauxrep2`, which takes the path to an existing `p_aux` file and a cache directory path. It creates and writes a new `p_aux` and returns the corresponding `comm_r`. No replica or tree files are written, so it is the caller's responsibility to provide them (and they must match the `comm_r_last` in the provided `p_aux`).
Caveat: totally untested. If @cryptonemo can plumb through the API, maybe @travisperson can test before we merge. I won't have time to look at this more for a little while, but this might be enough for us to gain confidence and push this through soon.

Implement fauxrep2.

---

Cargo.toml
README.md
fil-proofs-tooling/Cargo.toml
fil-proofs-tooling/src/metadata.rs
filecoin-proofs/Cargo.toml
sha2raw/Cargo.toml
sha2raw/src/platform.rs
storage-proofs/core/Cargo.toml
storage-proofs/core/src/crypto/mod.rs
storage-proofs/core/src/crypto/pedersen.rs
storage-proofs/core/src/drgraph.rs
storage-proofs/core/src/hasher/pedersen.rs
storage-proofs/core/src/hasher/sha256.rs
storage-proofs/core/src/parameter_cache.rs
storage-proofs/porep/Cargo.toml
storage-proofs/porep/src/drg/vanilla.rs
storage-proofs/porep/src/stacked/vanilla/cache.rs
storage-proofs/porep/src/stacked/vanilla/challenges.rs
storage-proofs/porep/src/stacked/vanilla/create_label.rs
storage-proofs/porep/src/stacked/vanilla/encoding_proof.rs
storage-proofs/porep/src/stacked/vanilla/graph.rs
storage-proofs/porep/src/stacked/vanilla/labeling_proof.rs
storage-proofs/porep/src/stacked/vanilla/macros.rs
storage-proofs/porep/src/stacked/vanilla/params.rs
storage-proofs/post/Cargo.toml
storage-proofs/post/src/election/vanilla.rs
storage-proofs/post/src/fallback/vanilla.rs

feat: allow for compilation on aarch64

---

storage-proofs/core/src/crypto/feistel.rs

The range of the output of a feistel round should be modulus `n` which is strictly less than `n`.

Update range for feistel tests

---

storage-proofs/core/src/settings.rs
storage-proofs/porep/src/nse/vanilla/labels.rs
storage-proofs/porep/src/nse/vanilla/porep.rs

fix: update merkletree inconsistent usage as lc trees

fix: update tree usage when using the gpu builder

---

filecoin-proofs/src/bin/phase2.rs

Allows phase2 to verify non-raw to raw contributions.

feat: verify non-raw to raw param transitions in phase2-cli

---

filecoin-proofs/src/bin/phase2.rs

Phase2-cli incorrectly labeled the small initial params as raw.

fix: phase2-cli paramgen and filename parsing

---

storage-proofs/core/Cargo.toml
storage-proofs/core/src/hasher/types.rs
storage-proofs/porep/Cargo.toml
storage-proofs/porep/src/nse/circuit/circuit.rs
storage-proofs/porep/src/nse/vanilla/nse.rs
storage-proofs/post/Cargo.toml

This PR replaces a stopgap @dignifiedquire had implemented as a replacement for the previous unpadded MD construction. It depends on changes in neptune to add domain separation tags and support for a number of distinct hashing functions built over the Poseidon permutation: https://github.com/filecoin-project/neptune/pull/43
The new hash function allows for preimages which are shorter than the 'natural' size of the permutation — but whose actual size must be known such that the actual length is encoded in the domain tag.
We need (or would like to have) such a hash function so we can use fewer layers in test sectors/circuits but still use generic arrays with statically-typed sizes as required by the neptune API. This usage fits ideally with the new 'constant length' hash type.
To facilitate …

Use (varied) constant-length vector to hash column roots.

---

filecoin-proofs/Cargo.toml
filecoin-proofs/src/bin/phase2.rs

The phase2-cli `merge` command merges large and small param files.
The final phase2 participant generates small-raw params, which are converted into non-raw using `phase2 convert`. The final small-nonraw params are then merged into the large initial params to produce the final `MPCParameters` file for a circuit.

feat: phase2-cli merge command

---

filecoin-proofs/src/bin/phase2.rs
filecoin-proofs/src/constants.rs

The `phase2` CLI has a new command called `split-keys` which allows to
split phase2 parameter output into parameters that can be used for
rust-fil-proofs.
I'm not done yet, the path handling is not robust enough. Though it would
be good to get early review.

feat: add tool to split phase2 parameters

---

filecoin-proofs/src/bin/phase2.rs

`phase2 parse` prints information about large or small non-ram params without having to deserialize the entire file (only deserializes 6 points). This is useful when verifying that small and large files are equivalent, e.g. can be used to verify the output of `phase2 merge`.

feat: phase2-cli parse command

---

filecoin-proofs/src/bin/phase2.rs

This PR:
1. Forces contributions to be written as small-raw params using the `Streamer` type.
2. Adds the option `phase2 contribute --seed` to set the 32 bytes of contribution entropy. This is used to make deterministic contributions, which is useful when testing.

feat: phase2-cli force small-raw contributions

---

scripts/verify-parameters-json.sh

This commit adds a script to verify that a `.params` file (and the corresponding
`.vk file`) is part of the `parameters.json` and has the correct checksums.
I extracted this script from this PR: https://github.com/filecoin-project/rust-fil-proofs/pull/1249

feat: add script to verify parameter checksums in parameters.json

---

scripts/pin-params.sh

This cluster is way faster to ingest data.
The `--local` option makes ingestion even faster (it will put the data
on one peer only while adding and pin everywhere at the end).
Additionally, we trigger pin requests in the main cluster (async) so that
params will be replicated by those nodes too (at some point, once they finish
to fetch them) from the collab cluster.

Feat: pin params to the filecoin collab cluster.

---

storage-proofs/core/src/gadgets/por.rs

Avoid needless intermediate conversions to/from `Vec<bool>`  when converting `usize` to `Vec<bool>`. Current public input representation for the `PoR` circuit trivially encodes challenges as the corresponding `Fr`, so nothing more is required.
NOTE: when we do pack more efficiently, it will not be necessary to restore the logic replaced here. Then we can use bit-shifting (`<<`) and bitwise or (`|`) (or `+`) to keep input generation cheap. [EDIT: We will *not* be able to use a simple conversion from `u64` then — and the `try_from` used here is meant as a reminder not to. Instead, we will need a way to assemble an appropriate `FrRepr` directly. Alternately, we can trade some performance for simplicity and build up the result with `Fr` operations on individual challenges.] 
Hat tip to …

Eliminate wasteful PoR public-input conversions.

---

storage-proofs/core/src/multi_proof.rs

Instead of decompressing as we read proofs, first read them all into a buffer and decompress in parallel.
Thanks to @simonatsn and @sean-sn for noticing and submitting an improvement (adapted here).

Decompress proofs in parallel.

---

filecoin-proofs/src/api/post.rs
filecoin-proofs/src/api/seal.rs
rust-fil-proofs.config.toml.sample
storage-proofs/core/Cargo.toml
storage-proofs/core/src/compound_proof.rs
storage-proofs/core/src/settings.rs

This PR integrates lotus-blst in order to accelerate the SNARK verification.
This feature can be enabled with the `use_lotus_blst` setting.

feat: accelerate SNARK verification

---

.circleci/config.yml
filecoin-proofs/src/api/post.rs
filecoin-proofs/src/api/seal.rs

This PR consists of three parts:
- fil-blst based verification to Window PoSt.
- Logging so that you can easily verify when fil-blst is used.
- a new CI job is added to run the tests that use the flt-blst code path with `use_fil_blst` enabled.
On the [CI logs](https://app.circleci.com/pipelines/github/filecoin-project/rust-fil-proofs/2318/workflows/2e947ebe-581c-4533-a015-0aadf4ff01d4/jobs/55260) you can see that fil_blst was used (search for `use_fil_blst=true`).

Make fil-blst usage in Window PoSt possible

---

storage-proofs/core/src/error.rs
storage-proofs/core/src/merkle/tree.rs
storage-proofs/post/src/fallback/vanilla.rs

Instead of just failing when trying to generate a Fallback PoSt which contains faulty sectors, instead return a new `FaultySectors` error which contains a vector of faulty `SectorId`s.
In order to make use of the information in the enhanced error, `filecoin-ffi` will need to handle:
https://github.com/filecoin-project/filecoin-ffi/blob/master/rust/src/proofs/api.rs#L606-L609
https://github.com/filecoin-project/filecoin-ffi/blob/master/rust/src/proofs/types.rs#L253-L258
This might entail a breaking change of the `filecoin-ffi` consumed by Go, but the current change to `rust-fil-proofs` is purely additive. It just adds a new, more informative, error in a case where an error would already have been returned.
The included test should give a clear example of how to extract the faulty …

Add FaultySectors error to Fallback PoSt.

---

fil-proofs-tooling/src/bin/settings/main.rs

Improve the code of the `settings` tool. Now the settings are destructured,
this way whenever a new setting will be introduce there will be a compile
error.
Those are the things to be done while waiting for CI.

chore: destructure settings in settings bin

---

filecoin-proofs/src/api/post.rs
filecoin-proofs/src/types/mod.rs
filecoin-proofs/tests/api.rs
storage-proofs/core/src/compound_proof.rs
storage-proofs/post/src/fallback/vanilla.rs

An alternate PR/proposal to #1269.  Winning PoSt is not working at the moment.

feat: split up window post API into separate calls

---

filecoin-proofs/src/api/post.rs
filecoin-proofs/src/api/seal.rs
storage-proofs/post/src/fallback/compound.rs
storage-proofs/post/src/fallback/vanilla.rs

Sector IDs are more often included in log messages/attached to errors.
This PR is based on @IPFS-grandhelmsman work at #1261.
Closes #1261.
I've only gone over the files that were suggested in #1261, if there are more places where logging should be added, please let me know.

fix: improve sector ID logging

---

filecoin-proofs/src/api/post.rs
filecoin-proofs/tests/api.rs

This is in the context of generating a single vanilla proof.  A specialized post config should not be required.

fix: remove artificial requirement that config sector count be 1

---

storage-proofs/porep/src/stacked/vanilla/proof.rs

So we can refactor and optimize labeling with confidence, here are some test vectors locking in current behavior.

Add labeling test vectors.

---

storage-proofs/porep/src/stacked/vanilla/create_label/multi.rs
storage-proofs/porep/src/stacked/vanilla/memory_handling.rs

This PR removes the special handling of layer 1 and uses two producers on all layers. This should never be worse than having only a single producer, and may improve the situation if some configuration is penalized (as possibly observed) by a too-slow producer (perhaps because of slower RAM). I have benchmarked this, and it is no worse (but also no better) than what it replaces on 3970x.
I also cleaned up the `reset` function in `memory_handling.rs`. If we want the `debug!` changes from #1295, we could include that here too.

Use two producers in all layers.

---

storage-proofs/porep/src/lib.rs
storage-proofs/porep/src/stacked/vanilla/macros.rs

Co-authored-by: Wang Maozhang <wangmaozhang@huawei.com>
This implement prefetch marco for aarch64 in `storage-proofs/porep/src/stacked/vanilla/macros.rs`, with prefetch hints merged into core_arch library [rust-lang/stdarch-PR918](https://github.com/rust-lang/stdarch/pull/918) and [rust-lang/rust-PR77259](https://github.com/rust-lang/rust/pull/77259).
Patch delivers about 23% performance improvement in `(lotus-bench seal: preCommit phase 1)` with `--sector-size=512MB/32GiB` on Kunpeng920 aarch64 server.

feat(storage-proofs-porep): implement prefetch macro for aarch64

---

.circleci/config.yml
README.md
storage-proofs/core/src/settings.rs
storage-proofs/porep/Cargo.toml
storage-proofs/porep/src/stacked/vanilla/cores.rs
storage-proofs/porep/src/stacked/vanilla/create_label/multi.rs
storage-proofs/porep/src/stacked/vanilla/memory_handling.rs
storage-proofs/porep/src/stacked/vanilla/mod.rs

In order to maximize replication (precommit phase 1) performance, bind all replication threads to a single core (distinct from other replication threads). Consumer and producer threads for each replication task should be on cores which share cache. If multiple such cores exist, keep threads for a single replication task together (on cores sharing a cache). Otherwise, group cores based on the number of threads required. We create groups even when they do not correspond to a shared cache in order to make use of the core binding facility used in the preferred case.
If a core cannot be bound, a message will be logged in a debug mode, but operation is not interrupted. The thread is simply scheduled without constraint as though no attempt to bind a core had been made.
NOTE: This implementation …

bind replication threads to specific cores

---

storage-proofs/post/src/fallback/vanilla.rs

The log message was wrong. It's about the hash of the concatenated
`comm_c` and `comm_r_last`.
This was brought up at
https://github.com/filecoin-project/rust-fil-proofs/issues/1308#issuecomment-706824651
For the notation I used `||` for concatenation as in the comment above.
I don't know about notations for hashes. I'm more familiar with `++` or `.` as concatenation
operator (in programming languages).

fix: fix log message

---

fil-proofs-tooling/src/bin/settings/main.rs
filecoin-proofs/src/api/post.rs
filecoin-proofs/src/api/seal.rs
storage-proofs/core/src/crypto/pedersen.rs
storage-proofs/core/src/parameter_cache.rs
storage-proofs/core/src/settings.rs
storage-proofs/core/src/util.rs
storage-proofs/porep/src/stacked/vanilla/cache.rs
storage-proofs/porep/src/stacked/vanilla/cores.rs
storage-proofs/porep/src/stacked/vanilla/create_label/multi.rs
storage-proofs/porep/src/stacked/vanilla/graph.rs
storage-proofs/porep/src/stacked/vanilla/proof.rs
storage-proofs/post/src/fallback/circuit.rs

Settings don't need to be protected by a Mutex. Apart from being unnecessary, this also led to a recent difficult-to-debug problem when the Mutex was mistakenly held too long in a draft of #1305. (This forced independent threads to work sequentially, eliminating the benefits of parallelism.) We should avoid making it easy to accidentally introduce such performance degradations, especially since they could go unnoticed if not specifically being looked for.

Remove Mutex from settings

---

filecoin-proofs/src/bin/circuitinfo.rs
filecoin-proofs/src/bin/paramcache.rs
filecoin-proofs/src/constants.rs

@nicola asked how many constraints are in one (presumably 32 GiB) Winning PoSt.
This PR adds a CLI tool, `circuitinfo` which counts constraints, public inputs, and partitions (as appropriate) for any circuit and sector size. Usage can be deduced from the example below. Available circuit types are `--winning`, `--window`, and `--porep`. Each desired type must be specified individually.
The example output below also contains the answer to the question at hand.
In the future, and as needed, this tool could be enhanced to provide other information about 'realistic' circuits.
Usage and all the relevant output for v28 circuits.
```
(base) ➜  rust-fil-proofs git:(feat/count-circuit-constraints) ✗ time cargo run --release --bin circuitinfo -- --winning --window --porep
Finished release …
```

Add circuitinfo CLI tool to count circuit constraints.

---

filecoin-proofs/tests/api.rs

There is a short running version, which doesn't run the proofs and
a longer running one, which does run the proofs.
Currently tests fail when the proofs are running. I don't know why,
perhaps I'm removing files that are needed/not keeping files around
that should be kept.
It can easily be reproduced locally via:
RUST_LOG=debug cargo test test_resumable_seal -- --ignored --nocapture
@cryptonemo Can you please have a look at the test itself, if it does what
you expect and then please also check why it is failing?

 test: add test for resumable sealing

---

filecoin-proofs/src/types/mod.rs
filecoin-proofs/tests/api.rs

Use `DefaultOctTree` and `DefaultOctLCTree` instead of `Tree` and `LCTree`.

fix: remove no longer used exports

---

storage-proofs/porep/src/nse/circuit/compound.rs
storage-proofs/porep/src/nse/vanilla/challenges.rs
storage-proofs/porep/src/nse/vanilla/proof_scheme.rs

[Currently](https://github.com/filecoin-project/rust-fil-proofs/blob/1abb69ebeafdd938f25f6a4ef70664f63af4659d/storage-proofs/porep/src/nse/vanilla/proof_scheme.rs#L117), NSE porep derives the same challenges for every partition. This PR makes it so that each partition has a unique challenge set.

fix: nse porep challenge derivation

---

fil-proofs-tooling/Cargo.toml
fil-proofs-tooling/src/bin/fdlimit/main.rs
storage-proofs/porep/Cargo.toml
storage-proofs/porep/src/stacked/vanilla/proof.rs

feat: add tool that shows max available open files

feat: raise soft fdlimit to max at runtime (os x/linux)

---

phase2/src/lib.rs
phase2/tests/large.rs
phase2/tests/small.rs

fix: disable phase2 tests that require external files 

---

storage-proofs/porep/src/stacked/vanilla/proof.rs

Don't try to build more than one tree on the GPU at a time. There is no benefit to this, since tree building already uses the GPU's compute as efficiently as it's able, and it causes problems. The GPU tree builder was not designed to be used in this way.
This assumes only a single GPU is available for building trees, but that assumption was already present. We can overcome that limitation with multi-GPU scheduling, which is coming.

Serialize GPU tree building with GPU lock.

---

.circleci/config.yml

Aims to resolve #1361 
Enabled metrics-capture to test CI -- will remove if successful before merging.

fix: update paramcache run for metrics capture CI job

---

.circleci/config.yml
fil-proofs-tooling/Cargo.toml
filecoin-proofs/tests/api.rs
phase2/tests/large.rs
phase2/tests/small.rs
storage-proofs/core/src/fr32.rs
storage-proofs/core/src/parameter_cache.rs
storage-proofs/porep/src/stacked/vanilla/cache.rs
storage-proofs/porep/src/stacked/vanilla/proof.rs

ci: parallelize test runs accross packages

---

storage-proofs/porep/src/stacked/vanilla/proof.rs

It will only 'add_columns' once for each tree and then jump to next tree in current implemention.

fix tree-c and tree-r-last generation in GPU mode

---

README.md
storage-proofs/porep/src/stacked/vanilla/proof.rs

fix: ensure batch size and column_write_batch_size are consistent

doc: update readme and fix some typos

---

storage-proofs/core/src/gadgets/por.rs

This PR adds a PoR gadget which does not add a public input for the PoR challenge. This allows the caller circuit to pack multiple challenges into a single public input.
This gadget may be integrated into SDR (with some refactoring) and/or used in NSE window-post's window-tree PoR's.

feat: PoR no public input gadget

---

fil-proofs-tooling/src/bin/benchy/window_post.rs
storage-proofs/porep/src/stacked/vanilla/proof.rs
storage-proofs/porep/src/stacked/vanilla/proof_scheme.rs

Window post bench preserve_cache option should only be used on new/non-existent cache dirs.  This check enforces this.
This PR also removes an unrelated unused argument.

Improve preserve cache

---

storage-proofs/post/src/fallback/vanilla.rs

This improves the parallelism during both vanilla `prove` and vanilla `verify`.

perf(storage-proofs-post): increase parallelism in fallback-post

---

.circleci/config.yml
storage-proofs/porep/Cargo.toml
storage-proofs/porep/src/stacked/vanilla/cores.rs
storage-proofs/porep/src/stacked/vanilla/proof.rs

feat: add checkout_cores test to CI, run single threaded
doc: fix typo
A possible way to address #1378

fix: put checkout_cores test behind a single-threaded feature

---

.circleci/config.yml
storage-proofs-porep/src/stacked/vanilla/proof.rs

This PR supersedes #1420 — since we have decided to keep `neptune/opencl` behind the `gpu2` feature flag for now.
@vmx Can you rebase your CI work on this branch and continue here? I made one modification to the line that actually runs the lifecycle tests. The previous version didn't set the flags, but the new one should correctly specify `gpu2`.

Optimize tree-building for neptune/opencl (gpu2 flag).

---

storage-proofs-porep/Cargo.toml

Hi,
As of now, if `FIL_PROOFS_USE_MULTICORE_SDR == 1`, `sha2::compress256` is used to hash the data in `Phase 1`.
The function `sha2::compress256` is provided with feature `compress` of sha2.
But for aarch64, only with feature `compress`, the `sha2::compress256` does not use the aarch64 accelerators, e.g. `sha256su0`, but degradats to `soft_compress`.
According to our tests, that ~x6 slower than the ASM one.
We should add feature `asm` to enable those aarch64 accelerators as the code [1] in `sha2` shows.
Due to the compile BUG of `sha2` fixed by PR `https://github.com/RustCrypto/hashes/pull/207`, commited as `78f00c5f6d218`, we need a git dependency here.
In addition, to keep `x86` use only `compress` of sha2 as before, we need add `-Zfeatures=itarget` to support conditional compilation …

feat: use feature [compress, asm] of sha2 for aarch64

---

filecoin-proofs/src/api/mod.rs
filecoin-proofs/tests/api.rs
storage-proofs-porep/src/drg/vanilla.rs
storage-proofs-porep/src/lib.rs
storage-proofs-porep/src/stacked/vanilla/porep.rs
storage-proofs-porep/tests/drg_vanilla.rs
storage-proofs-porep/tests/stacked_vanilla.rs

Refactors extraction to overwrite the provided data, rather than allocating another one.

fix: avoid one in memory copy for unsealing

---

filecoin-proofs/src/api/post_util.rs
filecoin-proofs/src/api/seal.rs
storage-proofs-core/src/compound_proof.rs
storage-proofs-porep/Cargo.toml
storage-proofs-porep/src/stacked/vanilla/memory_handling.rs
storage-proofs-porep/src/stacked/vanilla/proof.rs

Aims to resolve #1435 and investigate #1426

Remove deprecated code warnings and minor perf improvements

---

fil-proofs-tooling/src/bin/circuitinfo/main.rs

The `circuitinfo` binary is incorrectly named `paramcache` in its cli.

fix(fil-proofs-tooling): fix circuitinfo's binary name

---

fil-proofs-param/Cargo.toml
fil-proofs-tooling/Cargo.toml

The older version of dialoguer had a dependency on zerioize that
was yanked, hence making builds fail.
I've tried out some of the tools using `dialoguer` locally.
- `circuitinfo`: seems to do the correct thing interface wise, but it didn't print any information for me. I can't tell if it worked before or not
- `paramcache`: the output isn't as smooth I remembered it (but I can't tell if it was the same prior to this change, but i suspect it was), but it seems to work properly
- `paramfetch`: seems to work as expected
So I think this PR is OK to be merged.

fix: use latest version of dialoguer

---

.circleci/config.yml

The non-gpu tests run a long time, split them so that they can run
in parallel.
This makes the total runtim on CI go down from 78mins to 40mins.

chore: split non-gpu tests

---

.circleci/config.yml
fr32/src/reader.rs
sha2raw/src/platform.rs

feat: add aarch64 CI jobs to ensure proper baseline support

fix: avoid unsupported sha256_intrinsics on aarch64 (regression)

---

sha2raw/Cargo.toml
sha2raw/src/platform.rs

fix: update call based on updated version

feat: update sha2-asm dependency version

---

filecoin-proofs/Cargo.toml
filecoin-proofs/src/caches.rs

feat: use OnceCell for srs key caches to avoid duplicate generation

---

storage-proofs-porep/src/stacked/vanilla/create_label/multi.rs

I met some miner reports that there are too many (sometimes even millions of) "PRODUCER NOT READY" logs for each layer.
I think we can lower its log level.

chore: improve 'PRODUCER NOT READY' log

---

Cargo.toml
fil-proofs-param/Cargo.toml
fil-proofs-tooling/Cargo.toml
filecoin-hashers/Cargo.toml
filecoin-proofs/Cargo.toml
fr32/Cargo.toml
storage-proofs-core/Cargo.toml
storage-proofs-porep/Cargo.toml
storage-proofs-porep/src/stacked/vanilla/proof.rs
storage-proofs-post/Cargo.toml

Requires https://github.com/filecoin-project/bellperson/pull/203

feat: swap out default backend from pairing to blst

---

Cargo.toml
storage-proofs-porep/Cargo.toml
storage-proofs-porep/src/stacked/vanilla/proof.rs

This avoids all deadlocks as so far observed. Also uses a more flexible channel
for sync
Depends on https://github.com/filecoin-project/bellperson/pull/204

fix: switch to yastl thread pool

---

storage-proofs-porep/src/stacked/vanilla/create_label/multi.rs
storage-proofs-porep/src/stacked/vanilla/graph.rs
storage-proofs-porep/src/stacked/vanilla/utils.rs

Based on #1477 this updates the parent selection logic in multicore sdr. 
It **does not** implement the bitmask update, as that is not thread safe, and only the thread that fills the buffer is allowed to set this value. This I missed in my earlier review.

Improve multicore SDR

---

storage-proofs-porep/src/stacked/vanilla/create_label/multi.rs
storage-proofs-porep/src/stacked/vanilla/graph.rs
storage-proofs-porep/src/stacked/vanilla/utils.rs

Reverts filecoin-project/rust-fil-proofs#1501
More testing is needed, to isolate a specific error.

Revert "Improve multicore SDR"

---

.circleci/config.yml
README.md
fil-proofs-param/Cargo.toml
fil-proofs-tooling/Cargo.toml
filecoin-hashers/Cargo.toml
filecoin-proofs/Cargo.toml
fr32/Cargo.toml
storage-proofs-core/Cargo.toml
storage-proofs-porep/Cargo.toml
storage-proofs-porep/src/stacked/vanilla/proof.rs
storage-proofs-post/Cargo.toml

The latest versions of the gpu dependencies contain support for CUDA. Therefore
the `gpu` feature is split into `cuda` and `opencl`. By default only `opencl` is
enabled.
BREAKING CHANGE: The `gpu` feature is replaced by the `opencl` feature.

fix: upgrade to latest versions

---

.circleci/config.yml
README.md
storage-proofs-core/src/settings.rs

It's possible to compile rust-fil-proofs to make it run on CUDA instead
of OpenCL. This change also includes the introduction of two new environment
variables. One to control, whether OpenCL or CUDA should be used. The other
to tweak `nvcc` options.

fix: properly implement and document cuda feature

---

storage-proofs-porep/src/stacked/vanilla/proof.rs

The GPU tree builder (Neptune) only supports Poseidon hashes. Switch
to the CPU tree builder if other hash algorithms are used (which isn't
the case in Filecoin at the moment).
Closes #1512.

fix: use GPU tree builder only for Poseidon hashes

---

.circleci/config.yml

A recent addition to CI are the gpu tree builder tests with the `ignore`
flag. Enabling those added a lot to the run time of a single job. Hence
split them into a separate job, so that the total run time of all the CI
is shorter again.
The "ignored" tests still take a long time to run, but at least the overall run time is a bit better.

chore: split gpu tree builder CI jobs

---

filecoin-proofs/Cargo.toml

You can't use the multicore-sdr feature through filecoin-proofs in current implemention.

expose 'multicore-sdr' feature

---

fil-proofs-param/src/bin/paramcache.rs

The command line argumens `--only-post` and `--only-sector-update` are mutually
exclusive. With this commit you'll get an error message if both are used at the
same time:
error: The argument '--only-sector-update' cannot be used with one or more of the other specified arguments
USAGE:
paramcache --api-version <SEMANTIC VERSION> <--only-post|--only-sector-update>
For more information try --help

fix: make arguments mutually exclusive

---

filecoin-proofs/src/api/update.rs

**This PR is mostly intended to indicate where I think a bug exists**
I'm not entirely sure whether this is the right fix, but something around the cache path here seems to be wrong, causing most users on SnapNet to be unable to upgrade their sectors (see https://github.com/filecoin-project/lotus/issues/7968).
We may only want to be setting the path in some of the use cases for this method.

fix: correctly set cache path for empty sector update proofs

---

filecoin-proofs/src/api/update.rs
storage-proofs-update/src/vanilla.rs

Fix empty sector update priority and add debugging

---

storage-proofs-update/src/challenges.rs
storage-proofs-update/src/circuit.rs
storage-proofs-update/src/circuit_poseidon.rs
storage-proofs-update/src/constants.rs
storage-proofs-update/src/lib.rs
storage-proofs-update/src/poseidon/circuit.rs
storage-proofs-update/src/poseidon/compound.rs
storage-proofs-update/src/poseidon/mod.rs
storage-proofs-update/src/poseidon/vanilla.rs
storage-proofs-update/src/vanilla.rs
storage-proofs-update/tests/circuit_poseidon.rs
storage-proofs-update/tests/common/mod.rs
storage-proofs-update/tests/compound.rs

Signed-off-by: Jakub Sztandera <kubuxu@protocol.ai>

Poseidon version of SnapDeals

---

README.md
fil-proofs-tooling/src/bin/benchy/main.rs
fil-proofs-tooling/src/bin/benchy/prodbench.rs
fil-proofs-tooling/src/bin/benchy/window_post_fake.rs
fil-proofs-tooling/src/bin/benchy/winning_post.rs
fil-proofs-tooling/src/bin/gpu-cpu-test/main.rs
fil-proofs-tooling/src/shared.rs

feat: extend winning_post bench to allow fake seals
feat: add a window_post_fake bench for using fake seals
feat: bump default API version in both PoSt benches to current
docs: update documentation on bench usage

Improve PoSt benches

---

.circleci/config.yml

Instead of using `paramfetch`, which is using `ipget`, get the file
via HTTP. This should solve problems with the CI job timing out.

chore: CI times out due to ipget issues

---

.circleci/config.yml

In CircleCI you cannot restore a cache on macOS that was saved on Linux.
The workaround is to persist those files in a workspace. That workspace
can then be attached on macOS. So the workflow for macOS is:
1. (Linux) Generate parameters and cache them
2. (Linux) Restore cache and preserve in workspace
3. (macOS) Attach workspace

chore: CI: use parameter cache also for macOS

---

filecoin-proofs/src/api/window_post.rs

This improves the parallelism when generating merkle tree.

perf(filecoin-proofs): increase parallelism in window-post

---

.circleci/config.yml

It probably was a debug left-over from the sector upgrade work. The
`test_seal_lifecycle_upgrade` test is included when running with
the default test arguments, so there's no need to mention it separately.
It was also run in the non-ignore case. There's no point of running
it twice.

chore: CI: don't always run test_seal_lifecycle_upgrade

---

.circleci/config.yml

Those tests run for a long time, release mode reduced the time. The
tests now run under 20mins, compared to over 1h prior to this commit.

chore: CI: run no GPU tests in release mode

---

.circleci/config.yml

We use the `rust-toolchain` file in order to run things on a specific
version of Rust. Change the CI to use that version. Prior to this
commit it was using a nightly build, which was needed in the past,
but no longer.
The only exception is on ARM, where we still need nightly.

chore: most of CI now runs on the rust-toolchain defined version

---

storage-proofs-update/tests/compound.rs

The sector update compound tests take a long time to run, ignore them
by default, like other long running tests (e.g. the lifecycle ones).
The CI run for `test_arm_no_gpu` is reduced to about 30min (was 75min). `test_darwin` is down to about 45min (was 60min). The tree building "ignored" tests now obviously take longer to run, but still < 60min. The total run time on CI is down to 55min (was 75min).

chore: ignore sector update compound tests

---

storage-proofs-update/Cargo.toml

`storage-proofs-update` includes a lot of dependencies it isn't actually
using, this commit removes those.

chore: remove unused dependencies from storage-proofs-update

---

.circleci/config.yml

Split the tree building CI runs into the ones from `filecoin-proofs`
`+ storage-proofs-update` and the rest for the ignored tests. This
should get the total runtime of those tests down to about 30mins.

chore: CI: split gpu tree building test runs

---

.circleci/config.yml

Run the `storage-proofs-update` crate tests as for any other crate.
Also simplify some test logic a bit.

chore: CI: run storage-proofs-update tests

---

storage-proofs-porep/src/stacked/vanilla/create_label/multi.rs

This commit fixes a comment that was outdated. Originally three atomics
were used. With commit [a43f3a9dbb9ef76b0053a9639e638a0478337f32] the
atomic that is tracking which node the consumer is currently working on
was moved into the `CacheReader`.
[a43f3a9dbb9ef76b0053a9639e638a0478337f32]: https://github.com/filecoin-project/rust-fil-proofs/commit/a43f3a9dbb9ef76b0053a9639e638a0478337f32#diff-c1a5ea514dd1555f26b0c1c63a7435ef2804e8759e44de747904ed4bcb47bf20L230-L231
Closes #1602.

fix: SDR: update comment

---

fil-proofs-param/Cargo.toml
fil-proofs-param/src/bin/paramfetch.rs
fil-proofs-tooling/Cargo.toml
filecoin-hashers/Cargo.toml
filecoin-proofs/Cargo.toml
storage-proofs-core/Cargo.toml
storage-proofs-porep/Cargo.toml
storage-proofs-post/Cargo.toml
storage-proofs-update/Cargo.toml

1. Update minimum versions for in-workspace crates.
2. Use the tilde constraint to ensure that we don't update to the next minor version.
Otherwise, the next minor release (which will re-release the changes on master) will break anything depending on this release.
NOTE: we should also go ahead and _release_ those minor releases. This is kind of hard to test otherwise.

chore: lock versions to the correct minor, and update

---

.circleci/config.yml
storage-proofs-porep/src/stacked/vanilla/cores.rs

For multicore SDR it is important that the producer and conumers share the
same (L3) cache. Hence we bind specific cores to threads. Prior to this
change there was one multicore SDR job per group, even if the group could
accompany multiple of such jobs. If there were more jobs scheduled than
groups available, those additional jobs wouldn't use specific cores, but
whatever the operating system decided.
With this change, additional jobs are now put into the groups in case there
is enough space to accompany them.
Fixes #1556.

fix: SDR: make it possible to bind to cores if units > groups

---

storage-proofs-post/src/fallback/vanilla.rs

Sometimes it's unclear from which sector an error originates from,
hence include the sector ID in the log messages.

fix: more sector logging

---

.circleci/config.yml

Version 12.5.0 doesn't seem to be supported anymore, hence upgrade to the
latest non-beta release.
Simulators for iOS (which we don't need) are deleted, so that there's enough
space for the Filecoin params.

chore: update CircleCI to xcode 13.4.1

---

.circleci/config.yml

This PR adds new CI job that actually evaluates test coverage of the Proofs codebase. 
[Tarpaulin](https://github.com/xd009642/tarpaulin) tool is used for this purpose.
Current total coverage, which is 37%, obtained by running regular tests (no ignored/isolated/big tests). Invoking other tests causes too long job execution.
I consider following next steps in this direction:
- add more regular simple tests to improve coverage, as it is rather low currently;
- enforce current value by CI, to prevent merging PRs that reduce coverage;
- add coverage results exporting to codecov.

Tarpaulin coverage

---

filecoin-proofs/Cargo.toml
filecoin-proofs/tests/api.rs

This commit adapts the test to make the generated files read-only before a WindowPoSt is performed. This simulates the use case when you mount your sectors read-only after generation.

test: make sure that WindowPoSt also works on read-only files

---

storage-proofs-porep/src/stacked/vanilla/cores.rs

Core binding currently does not work if the lotus-worker process is limited to a subset of CPUs.
This PR prevents attempting to bind threads to a core that the process does not have access to.

Use current process binding to limit cpus that threads can be bound to

---

README.md

fix: Broken Links in README.md #1637

---

fil-proofs-param/src/bin/paramcache.rs
fil-proofs-tooling/src/bin/benchy/prodbench.rs
fil-proofs-tooling/src/bin/benchy/window_post.rs
fil-proofs-tooling/src/bin/circuitinfo/main.rs
fil-proofs-tooling/src/shared.rs
filecoin-proofs/benches/aggregation.rs
filecoin-proofs/benches/preprocessing.rs
filecoin-proofs/src/api/seal.rs
filecoin-proofs/src/constants.rs
filecoin-proofs/src/parameters.rs
filecoin-proofs/src/types/porep_config.rs
filecoin-proofs/tests/api.rs
filecoin-proofs/tests/mod.rs

[https://github.com/filecoin-project/rust-fil-proofs/issues/1632](url)

chore: Introduce PoRepConfig::new_groth16()

---

fil-proofs-tooling/src/bin/update_tree_r_cache/main.rs
filecoin-proofs/src/constants.rs
storage-proofs-core/src/merkle/builders.rs
storage-proofs-core/src/merkle/mod.rs
storage-proofs-porep/src/drg/vanilla.rs
storage-proofs-porep/src/stacked/vanilla/proof.rs
storage-proofs-post/tests/fallback_circuit.rs
storage-proofs-update/src/constants.rs

There were quite a few public type definitions, that were mostly replaced by the `SectorShape*` types. This commit cleans them up and moves them around if appropriate.
This should make the code easier to follow and the public API surface smaller.
BREAKING CHANGE: `BinaryLCMerkleTree`, `BinaryMerkleTree`, `BinarySubMerkleTree`, `LCMerkleTree`, `LCStore`, `MerkleStore`, `MerkleTree`, `OctLCMerkleTree`, `OctLCSubMerkleTree`, `OctLCTopMerkleTree`, `OctMerkleTree`, `OctSubMerkleTree`, `OctTopMerkleTree`, `QuadLCMerkleTree` and `QuadMerkleTree` are removed from the public interface.
---
This PR was triggered by a question about optimizing the GPU usage. I then dug deeper into the code to find out which tree sizes we are actually using and then found out that there are lots of types we don't …

fix: clean up tree definitions

---

.circleci/config.yml
Cargo.lock
fil-halo2-gadgets/Cargo.toml
fil-halo2-gadgets/src/boolean.rs
fil-halo2-gadgets/src/lib.rs
fil-proofs-tooling/src/metadata.rs

As a result of our latest weekly meeting, I'm going to submit series of PRs dedicated to improving documentation of our current Halo2 abstractions.
There are following arguments for doing so:
- Hopefully, it should make circuit's code more understandable by rest of the team;
- It can be useful for future Halo2 delivering to Lotus;
- It allows continuing further experimenting with Halo2 circuits codebase using already defined abstractions and keep track of their change without interfering Jake's work a lot.

halo2: Improve abstractions documenting

---

.circleci/config.yml
fil-halo2-gadgets/src/sha256.rs

This PR adds proper documentation with examples for `Sha256Chip`, `Sha256FieldChip` and `Sha256WordsChip` abstractions (and their configs).
Also it adds CI job for running documentation tests, which prevents docs from becoming stale.

Halo2: Add docs for SHA256 circuit-specific abstractions

---

storage-proofs-post/tests/fallback_vanilla.rs

- Adds Fallback-PoSt tests for version `ApiVersion::V1_2_0`.
- Tests that the challenge generation algorithm in `ApiVersion::V1_2_0` is incompatible with previous versions.

feat(storage-proofs-post): add grindability tests

---

filecoin-proofs/src/api/post_util.rs
filecoin-proofs/tests/api.rs
storage-proofs-core/src/api_version.rs
storage-proofs-core/src/drgraph.rs
storage-proofs-porep/src/stacked/vanilla/graph.rs
storage-proofs-post/src/fallback/compound.rs
storage-proofs-post/src/fallback/mod.rs
storage-proofs-post/src/fallback/utils.rs
storage-proofs-post/src/fallback/vanilla.rs
storage-proofs-post/tests/fallback_vanilla.rs

Some more details here:
https://github.com/filecoin-project/rust-fil-proofs/issues/1270

feat: fix the open 'grindability issue'

---

.circleci/config.yml
storage-proofs-porep/Cargo.toml
storage-proofs-porep/build.rs
storage-proofs-porep/src/lib.rs
storage-proofs-porep/src/stacked/vanilla/macros.rs

When using Rust nightly we are able to enable an optimization for aarch64.
With this change it's now possible to compile for aarch64 on stable rust,
while the optimization is still enabled when compiled with nightly.
A similar fix was made for bellperson at
https://github.com/filecoin-project/bellperson/pull/269
This fix can be tested even on x86_64 on Linux with cross compiling
for aarch64:
cargo build --target aarch64-unknown-linux-gnu
Fixes https://github.com/filecoin-project/rust-fil-proofs/issues/1652.

fix: make builds on stable and aarch64 possible

---

filecoin-proofs/src/api/seal.rs

Allows PC1's unreplicated data file to be `/dev/zero`.
Closes #1664 (however this PR does not include skipping TreeD building for empty sectors, which can be handled in another PR).

feat(filecoin-proofs): allow PC1 unreplicated data to be /dev/zero

---

fil-proofs-param/src/bin/paramcache.rs
fil-proofs-tooling/src/bin/benchy/prodbench.rs
fil-proofs-tooling/src/bin/benchy/window_post.rs
fil-proofs-tooling/src/bin/circuitinfo/main.rs
fil-proofs-tooling/src/shared.rs
filecoin-proofs/benches/aggregation.rs
filecoin-proofs/benches/preprocessing.rs
filecoin-proofs/src/api/fake_seal.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/seal.rs
filecoin-proofs/src/api/update.rs
filecoin-proofs/src/caches.rs
filecoin-proofs/src/types/porep_config.rs
filecoin-proofs/src/types/sector_class.rs
filecoin-proofs/src/types/sector_update_config.rs
filecoin-proofs/tests/api.rs
filecoin-proofs/tests/mod.rs
storage-proofs-core/src/api_version.rs

This PR allows for optional API features to be enabled within a supported range of `ApiVersion`s.
This PR is currently a draft because:
- It should be merged into master after the grindability fix PR [#1661](#1661) is merged.
- `enum ApiFeature` contains no variants, i.e. this PR does not add prospective API features such as Synthetic-PoRep

feat: add API features

---

storage-proofs-porep/src/stacked/vanilla/params.rs

An off-by-one error had caused `Labels::labels_for_last_layer` to return the second last layer.

fix(storage-proofs-porep): return last layer from Labels

---

fil-proofs-tooling/src/bin/benchy/main.rs
fil-proofs-tooling/src/bin/benchy/window_post.rs

feat: benchy window-post add parallels tasks

feat: benchy window-post add parallels tasks

---

fil-proofs-tooling/Cargo.toml
fil-proofs-tooling/build.rs
fil-proofs-tooling/src/metadata.rs

Description: When the benchy program is generated on the compilation server and copied to a non-git code server for testing, the report result cannot be output.

fix: Benchy test without git code cannot output result

---

Cargo.toml
fil-proofs-tooling/Cargo.toml
fil-proofs-tooling/src/metadata.rs

`heim` isn't maintained anymore. With the most recent rustix release, `bitflags` >= v1.3.1 is needed. But `heim` restrictits it to at most 1.2.x. This means that we cannot build the project anymore.
This commmit replace `heim` with `sysinfo`. The information it provides is not equal, but similar enough. Here is some example output before and after this change:
With `heim`:
SystemMetadata {
system: "Linux",
release: "6.1.0-5-amd64",
version: "#1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1 (2023-02-15)",
architecture: "x86_64",
processor: "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz",
processor_base_frequency_hz: 2000,
processor_max_frequency_hz: 4000,
processor_features: "FeatureInfo { extended_family_id: 0, extended_model_id: 8, family_id: 6, model_id: 142, stepping_id: 10, brand_index: 0, …

fix: replace heim with sysinfo

---

storage-proofs-porep/src/stacked/vanilla/graph.rs

[`copy_parents_data_inner`](https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs-porep/src/stacked/vanilla/graph.rs#L224) only uses base parents, so there's no need to fetch extension parents at the caller side.

optimize: copy_parents_data only needs base parents

---

filecoin-proofs/src/api/update.rs

Make the config configurations more obvious.

refactor: less mutability, clearer code

---

storage-proofs-porep/src/stacked/vanilla/proof.rs

As the number of layers must match the column arity, we can just use the coumn arity directly, without passing in the number of layers.

refactor: the number of layers must match the column arity

---

filecoin-proofs/src/api/seal.rs
storage-proofs-porep/src/stacked/vanilla/create_label/mod.rs
storage-proofs-porep/src/stacked/vanilla/create_label/multi.rs
storage-proofs-porep/src/stacked/vanilla/create_label/single.rs
storage-proofs-porep/src/stacked/vanilla/proof.rs
storage-proofs-porep/tests/stacked_vanilla.rs

This PR adds an API to do SDR without doing anything else.
Please note that it's split into two commits. The first one adds the API, the second one is a refacoring, which makes the API a bit clearer IMHO. It passes only on the path, which is the only thing that's really needed.

Add API to do only SDR

---

filecoin-proofs/src/commitment_reader.rs

`add_piece` operates in 64 bytes pieces. It's faster to operate in bigger chunks. This commits increases the buffer size to 4KiB. This makes adding a 32GiB piece about more than 2x faster. On the hardware I used it goes down from 14min to about 6min.

fix: make add_piece taking less time

---

storage-proofs-porep/src/stacked/vanilla/proof.rs

The TreeRLast generation is doing more things when called during the PoRep, than during the empty sector update (aka SnapDeals). Document those differences.

docs: document the TreeRLast generation

---

filecoin-proofs/src/api/window_post.rs

`new_from_reader` unnecessarily copies the bytes into a `Vec<u8>` in this case.

Remove unnecessary copy of proof bytes

---

storage-proofs-porep/src/stacked/vanilla/proof.rs

Instead of creating two configs, that depend on each other, create a single one in the most straightforward way.
---
Now that we had a release I'm trying to push general useful changes from my proofs bin work onto master piece by piece, so that I don't have to rebase them in the future.

refactor: make configuration more obvious

---

.circleci/config.yml

This commit bundles several improvements for CI
- Change MacOS resource class: move to a different MacOS resource class as the current one is deprecated.
- A new cache is used as the old one was broken for some PRs
- Use the CircleCI stock Rust image instead of a custom Docker image
- Make the saved cached a bit smaller via a garbage collected registry

chore: improve CI

---

fil-proofs-tooling/src/shared.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/seal.rs
storage-proofs-porep/src/stacked/vanilla/create_label/mod.rs
storage-proofs-porep/src/stacked/vanilla/proof.rs
storage-proofs-porep/tests/stacked_vanilla.rs
storage-proofs-update/tests/circuit.rs
storage-proofs-update/tests/circuit_poseidon.rs
storage-proofs-update/tests/compound.rs

Only rows of the TreeR get discarded. Hence hard-code all other cases to 0 to add clarity, that they don't discard any rows. This makes the code easier to follow and reason about.

fix: hard-code rows to discard

---

storage-proofs-porep/src/stacked/vanilla/params.rs

The parameter identifiers are not allowed to change. This commit adds a test to make sure that those identifiers won't change accidentally.

test: add test for parameter identifiers

---

filecoin-proofs/src/api/fake_seal.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/seal.rs
filecoin-proofs/src/api/update.rs
filecoin-proofs/src/api/util.rs
filecoin-proofs/src/types/private_replica_info.rs

`p_aux` and `t_aux` is dealt with throughout the code. In the update proofs API they are nicely put into functions. Move those functions into the common utility module and then use those in all places.
The update proofs API puts a restriction on using the Poseidon hasher. This restriction is kept as it makes sense for all cases where `p_aux` and `t_aux` is used.

refactor: refactor p_aux/t_aux handling into the util module

---

.circleci/config.yml
fil-proofs-param/Cargo.toml
fil-proofs-tooling/Cargo.toml
filecoin-proofs/Cargo.toml
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/seal.rs
filecoin-proofs/src/api/update.rs
filecoin-proofs/src/api/util.rs
storage-proofs-core/Cargo.toml
storage-proofs-core/src/settings.rs
storage-proofs-core/src/util.rs
storage-proofs-porep/Cargo.toml
storage-proofs-porep/src/stacked/vanilla/params.rs
storage-proofs-porep/src/stacked/vanilla/proof.rs
storage-proofs-post/Cargo.toml
storage-proofs-update/Cargo.toml

This PR introduces a new feature called `fixed-rows-to-discard`, when enabled, no `t_aux` files are written or read. It contains quite a lot of changes as some refactorings lead to less `StoreConfig`s and hence make it easier to reason about the whole change that it still does the correct thing.
This PR supersedes https://github.com/filecoin-project/rust-fil-proofs/pull/1715.

Allow sealing without t_aux files

---

storage-proofs-porep/src/stacked/vanilla/params.rs
storage-proofs-porep/src/stacked/vanilla/proof.rs

The Synthetic PoRep code is interleaved with the original PoRep code. This commit refactors the code, so that it's clearer what the differences between Synthetic and Non-Synthetic PoRep is, without the need to read through large parts of the code, looking for if-statements.
It also becomes more apparent in the code, that there are two "modes" of the `prove_layers` function in case of the Synthetic PoRep. One generation step in case there's no seed and one extracting step when there's a seed.
There no longer is a fallback in case from Synthetic PoRep to Non-Synthetic PoRep in case the Synthetic PoRep Proofs file cannot be read, but when the labels are set. I consider that a feature as if this case happens, your system likelt has some problems, so it's better to error early.

refactor: clearer Synthetic PoRep separation

---

fil-proofs-tooling/src/bin/gen_graph_cache/main.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/parameters.rs
storage-proofs-porep/src/stacked/circuit/column.rs
storage-proofs-porep/src/stacked/circuit/proof.rs
storage-proofs-porep/src/stacked/vanilla/challenges.rs
storage-proofs-porep/src/stacked/vanilla/params.rs
storage-proofs-porep/src/stacked/vanilla/proof.rs
storage-proofs-porep/src/stacked/vanilla/proof_scheme.rs
storage-proofs-porep/tests/stacked_circuit.rs
storage-proofs-porep/tests/stacked_compound.rs
storage-proofs-porep/tests/stacked_vanilla.rs

At the moment the challenges and the information about the number of layers is put into a single `LayerChallenges` struct. This misleads into thinking that the challenge generation is related to the number of layers, but it is *not*. `LayerChallenges` now only contains the information about challenges.
This makes the code eaier to follow, as it's now clearer, whether a function needs the layers or the challenges.

refactor: split challenges and layer information

---

filecoin-proofs/src/types/porep_config.rs

The `PoRepConfig::with_feature()` function is not used anywhere, hence remove it.

fix: remove with_feature

---

filecoin-proofs/src/parameters.rs

The function to select the challenges changes a lot over time and now is hardly comprehensible. Hence it's refacored into a more understandable version. It uses a `div_ceil` function which is expecte to be included in the Rust standard library at some point in the future.

refactor: better select challenges function

---

filecoin-proofs/src/types/porep_config.rs
storage-proofs-porep/src/stacked/circuit/proof.rs

There's no need to store the full public parameters within the `StackedCircuit` struct, as it only needs the number of layers.

refactor: StackedCircuit only needs the number of layers

---

storage-proofs-porep/src/stacked/circuit/column.rs
storage-proofs-porep/src/stacked/circuit/column_proof.rs
storage-proofs-porep/src/stacked/circuit/params.rs
storage-proofs-porep/src/stacked/circuit/proof.rs

Instead of passing in the number of layers through the public params, get the number of layers from the private inputs that are required anyway. The number of layers equals the number of columns of a columns proof.
---
I first wasn't really convinced that it makes sense, but after seeing that now [`circuit()` doesn't need the public params anymore](https://github.com/filecoin-project/rust-fil-proofs/compare/stacked-circuit-num-layers...stacked-circuit-remove-num-layers?expand=1#diff-ffb695bda5cb5ab675888466cd786c2dd9f6d1e9e60d52ce0aa4300c3020170bL296) it looks like a win to me.

refactor: get number of layers from private inputs

---

fil-proofs-tooling/src/bin/gen_graph_cache/main.rs
filecoin-proofs/src/parameters.rs
storage-proofs-porep/src/stacked/circuit/proof.rs
storage-proofs-porep/src/stacked/vanilla/challenges.rs
storage-proofs-porep/src/stacked/vanilla/mod.rs
storage-proofs-porep/src/stacked/vanilla/params.rs
storage-proofs-porep/src/stacked/vanilla/proof.rs
storage-proofs-porep/src/stacked/vanilla/proof_scheme.rs
storage-proofs-porep/tests/stacked_circuit.rs
storage-proofs-porep/tests/stacked_compound.rs
storage-proofs-porep/tests/stacked_vanilla.rs

This PR is a preparation for the non-interactive PoRep, where a new type of challenges will be introduced.
Though it also makes sense outside of this. A new `Challenges` enum is introduced, which add a bit more type safety. This way you cannot accidentally use e.g. the interactive PoRep challenges with the synthetic PoRep.
For more consistency the `SynthChallenges` struct renamed to `SynthChallengeGenerator`, so that we can have a `SynthChallenges` struct which corresponds to the `InteractiveChallenges` and upcoming `NiChallenges` struct.
For testing purpose it's now possible to add any feature (not just the Synthetic PoRep one). This is something that is needed for the NonInteractive PoRep, as well as the Resnaps work.
I've keep the individual commits for easier reviewing, the major …

refactor: Challenges enum

---

fil-proofs-tooling/src/bin/benchy/porep.rs
fil-proofs-tooling/src/bin/benchy/window_post.rs
fil-proofs-tooling/src/bin/benchy/window_post_fake.rs
fil-proofs-tooling/src/bin/benchy/winning_post.rs
fil-proofs-tooling/src/bin/gpu-cpu-test/main.rs
fil-proofs-tooling/src/shared.rs

All users were using a hard-coded PoRep ID for `create_replica()` already, hence we can remove that parameter and use `get_porep_config()` directly.

refactor: use new_groth16_with_feature

---

fil-proofs-tooling/src/shared.rs
filecoin-proofs/src/api/seal.rs
filecoin-proofs/src/constants.rs
filecoin-proofs/src/parameters.rs
filecoin-proofs/src/types/porep_config.rs
filecoin-proofs/tests/api.rs
storage-proofs-core/src/api_version.rs
storage-proofs-core/src/compound_proof.rs
storage-proofs-porep/src/stacked/vanilla/challenges.rs
storage-proofs-porep/src/stacked/vanilla/params.rs
storage-proofs-porep/src/stacked/vanilla/proof.rs

Adding non-interactive PoRep. It's similar to the interactive PoRep, but
it performance 12.6x the amount of proofs. In order to not overwhelm the
system with too many parallel proofs, they are split into batches of 10,
which then leads to a similar resource consumption per batch as for a
single interactive PoRep.

feat: non-interactive PoRep

---

fil-proofs-tooling/src/bin/benchy/main.rs
fil-proofs-tooling/src/bin/benchy/porep.rs
fil-proofs-tooling/src/bin/benchy/window_post.rs
fil-proofs-tooling/src/bin/benchy/window_post_fake.rs
fil-proofs-tooling/src/bin/benchy/winning_post.rs
storage-proofs-core/src/api_version.rs

Instead of passing in a boolean whether it's Synthetic PoRep or not, make it possible to pass in any supported feature.
This is a follow up of https://github.com/filecoin-project/rust-fil-proofs/pull/1742#discussion_r1430175595.

feat: benchy: add API features flag

---

README.md
filecoin-proofs/src/api/update.rs
filecoin-proofs/src/caches.rs
filecoin-proofs/tests/api.rs
storage-proofs-core/src/api_version.rs
storage-proofs-core/src/merkle/mod.rs
storage-proofs-core/src/settings.rs
storage-proofs-porep/src/stacked/vanilla/proof.rs
storage-proofs-update/src/vanilla.rs

This PR is a mix of smaller changes that I accumulated over the year. This PR should be reviewed on a commit by commit basis. I thought I bundle them in a single PR so that I don't have to rebase all of them all the time.
The review is not urgent, but I hope we can get all of those eventually merged.

Various improvements

---

fil-proofs-param/src/bin/paramcache.rs
fil-proofs-tooling/src/bin/circuitinfo/main.rs
filecoin-proofs/src/caches.rs
filecoin-proofs/src/constants.rs

Most tests rely on sector sizes being supported, but the constant we're using is named 'published sector sizes'.  This wouldn't normally matter, but the distinction is required for a future update and the naming is more clear (since not all supported sector sizes have published parameters).

Rename and separate published and supported sector sizes

---

README.md
storage-proofs-porep/src/stacked/vanilla/proof.rs
storage-proofs-update/src/vanilla.rs

For synth porep, we switch to threaded/parallel proof verification as an optimization.  This takes it a step further and now allows errors to be propagated/returned properly.
Note: There is a FIXME in the code that will be removed after it's properly tested via filecoin-ffi testing.

Improve error handling for threaded verification errors

---

filecoin-proofs/src/api/seal.rs

Alternative to #1754. This PR proposes that any PoRep challenge seed(s) (provided as API arguments) not be included in NI-PoRep's SnarkPack transcript, as opposed to using a constant value for NI-PoRep's challenge seed.
Imho, merging of either PR should be held off until a decision is made during the NI-PoRep audit.

fix: remove challenge seed from NI-PoRep SnarkPack transcript

---

filecoin-proofs/src/constants.rs

Changes the minimum number NI-PoRep challenges for test sectors from 4 to `ceil(12.8 * min_porep_challenges)` (i.e. 26 challenges) and the NI-PoRep partition count for test sectors from 2 to 13; bumping the partition count allows NI-PoRep test sectors to use their current Groth16 keys (i.e. 2 PoRep challenges per circuit/partition).

fix: increase ni-porep min challenges for test sectors

---

filecoin-proofs/src/api/seal.rs
filecoin-proofs/src/constants.rs
filecoin-proofs/tests/api.rs

feat: add tests to ensure NI-PoRep is tested w and w/o aggregation

feat: expose an API suitable for NI-PoRep proof aggregation

---

filecoin-proofs/src/api/seal.rs
filecoin-proofs/src/constants.rs
filecoin-proofs/tests/api.rs

feat: add negative bounds checking test
feat: add a 32GiB max value ni-porep aggregation test
In case this is needed in reference to https://github.com/filecoin-project/FIPs/pull/1018

feat: update FIP92 min value to proposed new value

---

.github/workflows/ci.yml
storage-proofs-porep/Cargo.toml
storage-proofs-porep/src/stacked/vanilla/cores.rs

When running `rust-fil-proofs` under Rust 1.81 the following warning is issued:
```
warning: the following packages contain code that will be rejected by a future version of Rust: bitflags v0.7.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```
The package depending on `bitflags` 0.7.0 is `hwloc`, which has been replaced by `hwloc2`.
Understandably, `hwloc` (the original library) has suffered  changes as well, which are reflected in `hwloc2`.
The main one being the removal of `allowed_cpuset`, according to the `hwloc` upgrading guide (https://www.open-mpi.org/projects/hwloc/doc/v2.8.0/a00374.php#upgrade_to_api_2x_allowed) these `cpuset` should be enough given that the …

fix: upgrade hwloc

---

fr32/src/reader.rs

Make things mutable and also silence a Clippy warning.

fix: make things compile on aarch64 again

---

fil-proofs-tooling/src/bin/benchy/porep.rs
fil-proofs-tooling/src/shared.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/tests/api.rs

`clear_layer_data()` and `clear_caches` are never called within `rust-fil-proofs` and also not used in `rust-filecoin-proofs-api`, hence remove them.
The `clear_cache()` and `clear_synthetic_proofs()` functions don't need to be generic over the tree as it's never used within those functions. This is a breaking change.
BREAKING CHANGE: signature of `clear_cache()` and `clear_synthetic_proofs()` changed. The generic parameter is no longer needed.
---
I've put this on master. I'll rebase it, once master is green.

fix: clean up public API for clearing files

---

fil-proofs-param/tests/support/mod.rs
fil-proofs-tooling/src/shared.rs

On a fresh checkout, there's no a warning on some `tempfile` usage. This commit fixes it.

chore: fix Clippy warnings
