.circleci/config.yml
filecoin-proofs/src/api/internal.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/sector_builder/scheduler.rs
filecoin-proofs/src/bin/paramfetch.rs
filecoin-proofs/src/bin/parampublish.rs
filecoin-proofs/src/lib.rs
sector-base/src/lib.rs
src/bin/bencher.rs
storage-backend/src/lib.rs
storage-proofs/src/circuit/beacon_post.rs
storage-proofs/src/circuit/drgporep.rs
storage-proofs/src/circuit/porc.rs
storage-proofs/src/circuit/ppor/mod.rs
storage-proofs/src/circuit/test/mod.rs
storage-proofs/src/circuit/vdf_post.rs
storage-proofs/src/example_helper.rs
storage-proofs/src/layered_drgporep.rs
storage-proofs/src/lib.rs
storage-proofs/src/test_helper.rs

chore: cleanup all rustc and clippy warnings

---

sector-base/src/io/fr32.rs

It seems from the implementation of `write_unpadded_aux` that an implicit precondition is that the raw data (being recovered) that generated the padded layout had to be a multiple of the size of a data unit (e.g., 254), that is, the padded byte array can't contain *extra* bits (see `PaddingMap` documentation).
This is also confirmed by the selection of the sizes in the tests,
https://github.com/filecoin-project/rust-proofs/blob/3d8d35bef2c6cd506a4851e9fe83b2f793db0d87/sector-base/src/io/fr32.rs#L792-L793
https://github.com/filecoin-project/rust-proofs/blob/3d8d35bef2c6cd506a4851e9fe83b2f793db0d87/sector-base/src/io/fr32.rs#L815-L818
This PR documents this and can also serve as as discussion place to see if this was an intended design decision. This needs to be clearly defined to help …

fr32: check `len` passed to `write_unpadded`

---

storage-proofs/src/crypto/feistel.rs
storage-proofs/src/drgraph.rs
storage-proofs/src/zigzag_graph.rs

This PR aims at (1) reflecting my current understanding of these modules to provide a useful context for future (concrete) questions I might have of the code and (2) leaving some documentation behind that may be useful for the next one reading this code for the first time.
Towards getting some more context around https://github.com/filecoin-project/rust-proofs/issues/455.

Add documentation to the `Graph` and `ZigZag` traits

---

filecoin-proofs/src/api/internal.rs

Closes #482.
This implements #482, more or less as described there.
I decided to:
- copy the input file to the output path
- mmap the copy
- replicate in place
- either
- delete the output file (in the case of a replication error)
- flush to ensure the data is written to the output file

Use mmap for replication in API.

---

filecoin-proofs/examples/ffi/main.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/responses.rs

The name of the PR says it all.

flatten PoSt proofs to make it easier to work with CGO

---

filecoin-proofs/examples/zigzag.rs

Exactly as the descriptions says. This will help with sector size calculations.

Add --bench-only option to bench circuit without replication or groth proving

---

storage-proofs/src/layered_drgporep.rs

Builds on top of https://github.com/filecoin-project/rust-fil-proofs/pull/509.
With a zigzag example of size 8192 there doesn't seem to be much difference,
```
Total: 309.4 MB
309.0  99.9%  99.9%    309.0  99.9% ::allocate_in (inline) /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/raw_vec.rs:109
0.3   0.1% 100.0%      0.3   0.1% ::reserve_internal (inline) /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/raw_vec.rs:683
0.1   0.0% 100.0%      0.1   0.0% sapling_crypto::jubjub::JubjubBls12::new (inline) ??:0
0.0   0.0% 100.0%      0.0   0.0% core::ptr::::is_null (inline) /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libcore/ptr.rs:1602
Total: 293.4 MB
293.0  99.9%  99.9%    293.0  99.9% ::allocate_in (inline) …
```

use anonymous map for aux replication

---

filecoin-proofs/src/bin/paramfetch.rs
filecoin-proofs/src/bin/parampublish.rs

simple pr to remove the interactive prompt when a parameter fails to be fetched

remove retry prompt

---

storage-proofs/src/layered_drgporep.rs

Reduces max resident size (maximum memory usage) during replication with zigzag (128MB  Sector)
- from `5,925,036 KB`
- to`3,172,848 KB`
by avoiding one round of cloning graphs. 
--- 
```
root: filecoin-proofs
Command being timed: "./target/release/examples/zigzag --taper-layers 7 --taper 0.3 --size 131072 --no-bench"
User time (seconds): 3108.83
System time (seconds): 5.66
Percent of CPU this job got: 594%
Elapsed (wall clock) time (h:mm:ss or m:ss): 8:44.27
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 5925036
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 1
Minor (reclaiming a frame) page faults: 2374081
Voluntary context switches: …
```

reducing replication memory

---

storage-proofs/src/drgporep.rs
storage-proofs/src/vde.rs

chore(storage-proofs): remove unused parameter _m in create_key

---

filecoin-proofs/Cargo.toml
filecoin-proofs/src/api/sector_builder/helpers/snapshots.rs
filecoin-proofs/src/api/sector_builder/kv_store/fs.rs
filecoin-proofs/src/api/sector_builder/kv_store/mod.rs
filecoin-proofs/src/api/sector_builder/kv_store/rocks.rs
filecoin-proofs/src/api/sector_builder/mod.rs
filecoin-proofs/src/api/sector_builder/scheduler.rs

feat(filecoin-proofs): implement rocksdb based kv

---

filecoin-proofs/Cargo.toml
filecoin-proofs/src/bin/paramfetch.rs
filecoin-proofs/src/param.rs

Closes https://github.com/filecoin-project/go-filecoin/issues/2488.
Progress bars look like this (I included an error case):

Add progress bar during parameter download

---

storage-proofs/Cargo.toml
storage-proofs/src/hasher/pedersen.rs

This is now supported in filecoin/pairing directly

refactor(storage-proofs): remove serde wrapper code

---

.circleci/config.yml
storage-proofs/Cargo.toml
storage-proofs/src/drgraph.rs
storage-proofs/src/hasher/pedersen.rs
storage-proofs/src/hasher/sha256.rs
storage-proofs/src/layered_drgporep.rs
storage-proofs/src/settings.rs

Based on https://github.com/filecoin-project/rust-fil-proofs/pull/567.
Closes https://github.com/filecoin-project/rust-fil-proofs/issues/647.

Provide an option to optimize either wall clock time of replication or memory

---

storage-proofs/Cargo.toml
storage-proofs/benches/blake2s.rs
storage-proofs/benches/encode.rs
storage-proofs/benches/fr.rs
storage-proofs/benches/merkle.rs
storage-proofs/benches/pedersen.rs
storage-proofs/benches/sha256.rs
storage-proofs/benches/xor.rs

Add and improve micro benchmarks

---

CONTRIBUTING.md

docs: add commit message guidelines

---

README.md

Now that I read it altogether this is not at all a straightforward optimization process, @porcuquine we're still missing a general profile configuration to optimize either for memory or speed that basically says "I don't care about the details, I have enough X resources, just make sure Y is as small as possible".
Closes #703.

feat(doc): add optimization strategies in README

---

filecoin-proofs/src/api.rs

- swap out functional comm_r generation for imperative to easily catch on errors and pass their information up
- incomplete test for `verify_post_fixed_sectors_count` to check the unhappy paths. would like to pull @laser in to have a more robust test for this function at this layer
resolves: https://github.com/filecoin-project/rust-fil-proofs/issues/566

pass BadFrBytes error up instead of panicking

---

README.md

Somehow this commit was missed when merging #760

docs: update readme for logging

---

parameters.json
storage-proofs/src/parameter_cache.rs

I forgot to publish these when doing the recent updates to the circuits.
Pinning is in progress.

chore: publish params v11

---

.circleci/config.yml
Dockerfile-ci
fil-proofs-tooling/Cargo.toml
fil-proofs-tooling/src/bin/benchy/zigzag.rs
fil-proofs-tooling/src/bin/micro.rs
fil-proofs-tooling/src/lib.rs
fil-proofs-tooling/src/metadata.rs
storage-proofs/Cargo.toml

Sample output below
```
{"git":{"hash":"46d471cf87a6c285085e324566c8e4a5fbb69e90","date":"2019-08-05T14:52:39Z"},"system":{"system":"Darwin","release":"18.7.0","version":"Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64","architecture":"x86_64","processor":"Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz","processor_base_frequency_hz":2900,"processor_max_frequency_hz":4800,"processor_features":"FeatureInfo { eax: 591594, ebx: 34605056, edx_ecx: SSE3 | PCLMULQDQ | DTES64 | MONITOR | DSCPL | VMX | EIST | TM2 | SSSE3 | FMA | CMPXCHG16B | PDCM | PCID | SSE41 | SSE42 | X2APIC | MOVBE | POPCNT | TSC_DEADLINE | AESNI | XSAVE | OSXSAVE | AVX | F16C | RDRAND | FPU | VME | DE | PSE | TSC | MSR | PAE | MCE | CX8 | APIC | SEP | MTRR | PGE | MCA | CMOV | PAT …
```

feat(fil-proofs-tooling): collect benchmark metadata

---

.circleci/config.yml
fil-proofs-tooling/scripts/benchy.sh
fil-proofs-tooling/scripts/micro-remote.sh

This changeset provides a script which will run the micro benchmarks on a remote server via SSH. It outputs the benchmark JSON to the client's stdout.

feat(run micro benchmarks remotely)

---

.circleci/config.yml
.gitignore
fil-proofs-tooling/README.md
fil-proofs-tooling/scripts/benchy-remote.sh
fil-proofs-tooling/scripts/benchy.sh
fil-proofs-tooling/scripts/micro-remote.sh
fil-proofs-tooling/scripts/micro.sh

Makes incremental progress towards #761 
This changeset includes a script which will run `benchy.sh` on a remote server via SSH and write its output to the client's stdout.

feat(run benchy remotely)

---

parameters.json

We accidentally published the wrong Groth parameters. We need to roll back to the VDF PoSt parameters.

feat(replace rational PoSt params and keys with VDF PoSt)

---

README.md

Add sections to readme for Pedersen Hash speed and memory optimizations.

Update readme to include Pedersen Hash window-size optimization

---

filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/fr32.rs

feat(filecoin-proofs): switch generate_piece_commitment to accept `io::Read`

---

fil-proofs-tooling/Cargo.toml
fil-proofs-tooling/src/metadata.rs
filecoin-proofs/Cargo.toml
storage-proofs/Cargo.toml

feat(deps): update and add gpu feature

---

fil-proofs-tooling/src/bin/benchy/hash_fns.rs
fil-proofs-tooling/src/bin/benchy/stacked.rs
filecoin-proofs/examples/stacked.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/post.rs
filecoin-proofs/src/bin/paramcache.rs
filecoin-proofs/src/bin/paramgen.rs
filecoin-proofs/src/caches.rs
filecoin-proofs/src/singletons.rs
storage-proofs/benches/pedersen.rs
storage-proofs/src/circuit/apex_commitment.rs
storage-proofs/src/circuit/drgporep.rs
storage-proofs/src/circuit/pedersen.rs
storage-proofs/src/circuit/por.rs
storage-proofs/src/circuit/porc.rs
storage-proofs/src/circuit/ppor/mod.rs
storage-proofs/src/circuit/rational_post.rs
storage-proofs/src/circuit/stacked/hash.rs
storage-proofs/src/circuit/stacked/proof.rs
storage-proofs/src/example_helper.rs

refactor: only use statically allocated Pedersen Hash params

---

storage-proofs/Cargo.toml
storage-proofs/benches/encode.rs
storage-proofs/benches/parents.rs
storage-proofs/src/circuit/drgporep.rs
storage-proofs/src/circuit/stacked/column.rs
storage-proofs/src/circuit/stacked/proof.rs
storage-proofs/src/crypto/pedersen.rs
storage-proofs/src/drgporep.rs
storage-proofs/src/drgraph.rs
storage-proofs/src/stacked/column.rs
storage-proofs/src/stacked/graph.rs
storage-proofs/src/stacked/params.rs
storage-proofs/src/stacked/proof.rs
storage-proofs/src/vde.rs

- maximize parallelism during replication
- generate column commitments during key generation
- optimize parents generation
- some smaller tweaks to go faster
replicating 512Mib with max caching enabled took `~11min`with this

perf(storage-proofs): optimize sdr replication

---

filecoin-proofs/src/api/seal.rs
storage-proofs/src/stacked/challenges.rs
storage-proofs/src/stacked/params.rs

Closes https://github.com/filecoin-project/go-sectorbuilder/issues/43

fix: remove unneeded restriction on the seal seed

---

filecoin-proofs/src/api/post.rs
storage-proofs/src/election_post.rs

also update the api to expect no more faulty sectors

fix: add missing election-post checks

---

filecoin-proofs/src/bin/paramcache.rs

This PR modifies paramcache such that it will generate keys and parameters for a set of user-provided sector sizes (specified in bytes).
Various CircleCI builds generate parameters, and most of them end up generating parameters and keys for sector sizes which they won't use.

feat(params): paramcache to generate params for whitelisted sizes

---

filecoin-proofs/parameters.json
filecoin-proofs/src/api/post.rs
storage-proofs/src/circuit/election_post.rs
storage-proofs/src/compound_proof.rs
storage-proofs/src/election_post.rs
storage-proofs/src/parameter_cache.rs

Updated parameters for election post

---

.circleci/config.yml
fil-proofs-tooling/src/bin/benchy/election_post.rs
fil-proofs-tooling/src/bin/benchy/main.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/seal.rs
filecoin-proofs/src/bin/paramcache.rs
filecoin-proofs/src/caches.rs
filecoin-proofs/src/parameters.rs
filecoin-proofs/src/types/porep_config.rs
filecoin-proofs/src/types/post_config.rs
filecoin-proofs/src/types/sector_class.rs

This does not really need to be exposed

refactor: unify window size handling

---

storage-proofs/src/stacked/params.rs
storage-proofs/src/stacked/proof.rs

fix: resolve flipped comm_q/comm_c usage

---

filecoin-proofs/src/api/mod.rs

Fixes #963 
If the call to extract_range was successful, the unsealed vector must have a length which equals num_bytes_padded. The byte at its 0-index byte will be the the byte at index offset_padded in the sealed sector.

fix(unseal): pass correct value to write_unpadded

---

scripts/pin-params.sh

The pin-params.sh with the fancy "last 3 versions" magic removed,
it
- verifies that you have a single version of the params in /var/tmp/filecoin-proof-parameters
- posts them to cluster via `ipfs-cluster-ctl`
- publishes the new cid to proofs.filecoin.io via `npx dnslink-dnsimple`
you need to install `ipfs-cluster-ctl` and a reasonable verion of node.js >= v10 at a guess.
see: https://dist.ipfs.io/#ipfs-cluster-ctl
see: https://www.npmjs.com/package/dnslink-dnsimple
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

feat: simplified pin-params.sh

---

fil-proofs-tooling/src/bin/benchy/election_post.rs
fil-proofs-tooling/src/bin/benchy/flarp.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/post.rs
filecoin-proofs/src/bin/paramcache.rs
filecoin-proofs/src/constants.rs
filecoin-proofs/src/parameters.rs
filecoin-proofs/src/types/post_config.rs
filecoin-proofs/src/types/sector_class.rs
storage-proofs/src/circuit/election_post.rs
storage-proofs/src/election_post.rs

- window sizes
- post challenge count
- post challenged nodes

feat: allow for more changes during benchmarking

---

fil-proofs-tooling/src/bin/benchy/flarp.rs
fil-proofs-tooling/src/bin/benchy/stacked.rs
filecoin-proofs/examples/stacked.rs
filecoin-proofs/src/constants.rs
filecoin-proofs/src/parameters.rs
filecoin-proofs/src/pieces.rs
storage-proofs/src/circuit/stacked/proof.rs
storage-proofs/src/stacked/params.rs
storage-proofs/src/stacked/proof.rs
storage-proofs/src/stacked/proof_scheme.rs

split window and wrapper degrees

feat: more configuration for degrees

---

storage-proofs/src/compound_proof.rs
storage-proofs/src/example_helper.rs

The build appeared broken for me, but this fixed it locally for continued testing.

fix: fix build

---

storage-proofs/src/stacked/graph.rs

After doing more benchmarks it showed that using `Vec<Vec<u32>>` has a
large memory overhead, when compared to a flattened `Vec<u32>`.
For sector size of `1 << 28` and `14` parents to cache, the resident
memory numbers are roughly
- `Vec<Vec<u32>>`:  21_289_684 kbytes
- `Vec<Box<[u32]>>`:  20_401_972 kbytes
- `Vec<u32>`: 14_681_016 kbytes

feat(storage-proofs): reduce size of the graph cache

---

filecoin-proofs/parameters.json
filecoin-proofs/src/bin/paramcache.rs
storage-proofs/src/hasher/pedersen.rs

Paramcache wasn't updated to use the correct hasher for PoSt, so now need to update those params

fix v22 params 

---

filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/post.rs

A PoSt proof including the same sector challenge index more than once is invalid, since it claims more winners than it proves. Return an error if a call to `post_verify` attempts this.

fix: error if duplicate challenges are passed to PoSt verification

---

filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/seal.rs
storage-proofs/src/stacked/params.rs

feat: add validation to check cache state and replica

---

fil-proofs-tooling/src/bin/benchy/election_post.rs
fil-proofs-tooling/src/bin/benchy/flarp.rs
fil-proofs-tooling/src/bin/benchy/shared.rs
fil-proofs-tooling/src/bin/gpu-cpu-test/election_post.rs
filecoin-proofs/src/api/mod.rs
filecoin-proofs/src/api/post.rs
filecoin-proofs/src/api/seal.rs
storage-proofs/src/stacked/proof.rs

fix: ensure proper replica path is used in gpu test

feat: add clear cache and validation to benches and tests

---

fil-proofs-tooling/src/bin/gpu-cpu-test/main.rs

Instead of having only a flag to run a single or two threads, change
the `parallel` option to a number, to define how many threads should
be run. The first thread/process is always a high priority one, the
other ones are low priority.
`1` means running only a single high priority proof (this is what
`--parallel false` was), `2` means running a high and a low priority
proof (this is what `--parallel true` was), higher numbers mean
one high priority proof and n-1 low priority ones.
This is the code I conducted my tests with for https://github.com/filecoin-project/bellman/pull/66#issuecomment-593459604.

feat: add support for running multiple low priority threads

---

fil-proofs-tooling/Cargo.toml
fil-proofs-tooling/src/bin/benchy/main.rs
fil-proofs-tooling/src/bin/benchy/merkleproofs.rs
storage-proofs/src/hasher/poseidon.rs

feat: allow merkleproof bench to use supported tree arities

feat: update merkleproof bench to use poseidon

---

sha2raw/Cargo.toml
sha2raw/src/sha256.rs
sha2raw/src/sha256_intrinsics.rs
sha2raw/src/sha256_utils.rs
storage-proofs/src/porep/stacked/vanilla/encoding_proof.rs
storage-proofs/src/porep/stacked/vanilla/labeling_proof.rs
storage-proofs/src/porep/stacked/vanilla/params.rs

fix(sha2raw): correctly loop over blocks in sha intrinsics

---

filecoin-proofs/parameters.json

feat: publish v24 params

---

storage-proofs/src/drgraph.rs

This PR makes the following changes to DRG parent generation:
- fixes an off by one error in the number of buckets
- removes unnecessary and dead code related to parent number addition
- fixes bugs introduced by improper casting
- makes explicit the type differences between DRG node indexes `u32` and metagraph node indexes `u64`, neither should be `usize`
- replaces `rng.gen_range()`
- changes the rng from `ChaCha20` to `ChaCha8`
- clarifies variable names
Closes #1065, #1067

fix: DRG parent generation

---

filecoin-proofs/src/bin/phase2.rs
storage-proofs/post/src/election/circuit.rs
storage-proofs/post/src/election/compound.rs
storage-proofs/post/src/election/vanilla.rs
storage-proofs/post/src/fallback/vanilla.rs
storage-proofs/post/src/rational/vanilla.rs

Side note: was planning to watch the CI process on this PR and may put add related updates here

feat: update election post to use flexible Tree structure

---

fil-proofs-tooling/src/bin/benchy/window_post.rs
fil-proofs-tooling/src/bin/benchy/winning_post.rs

Outputs some additional timings.

feat: add some more timing results to window post bench

---

.circleci/config.yml
storage-proofs/core/src/hasher/poseidon.rs
storage-proofs/core/src/hasher/sha256.rs
storage-proofs/core/src/merkle/tree.rs
storage-proofs/core/src/parameter_cache.rs

Updates name output where used in parameter file path generation.

feat: lowercase and remove special chars on parameter files

---

storage-proofs/core/Cargo.toml
storage-proofs/core/src/hasher/poseidon.rs
storage-proofs/core/src/hasher/types.rs
storage-proofs/porep/Cargo.toml
storage-proofs/porep/src/stacked/circuit/hash.rs
storage-proofs/porep/src/stacked/vanilla/hash.rs
storage-proofs/porep/src/stacked/vanilla/proof.rs
storage-proofs/post/Cargo.toml

needs https://github.com/filecoin-project/neptune/pull/16

no more match

---

filecoin-proofs/src/constants.rs

A similar comment exists in the actor code pointing back here.

Add comment to prompt coodinating wpost sector counts with actors code

---

fil-proofs-tooling/Cargo.toml
filecoin-proofs/Cargo.toml
storage-proofs/core/Cargo.toml
storage-proofs/core/src/gadgets/test/mod.rs
storage-proofs/porep/Cargo.toml
storage-proofs/post/Cargo.toml

needs 
- https://github.com/filecoin-project/phase2/pull/5 
- bellperson@0.8.0
- neptune@0.7.1

feat: integrate fixes to bellman and neptune

---

CODEOWNERS

Make me a global code owner so my PR approvals suffice to merge.

Make porcuquine a global code owner.

---

filecoin-proofs/src/api/post.rs
filecoin-proofs/tests/api.rs

fix: improve error handling of empty sector set

---

CHANGELOG.md
fil-proofs-tooling/Cargo.toml
filecoin-proofs/Cargo.toml
storage-proofs/Cargo.toml
storage-proofs/core/Cargo.toml
storage-proofs/porep/Cargo.toml
storage-proofs/post/Cargo.toml

feat: chore: release filecoin-proofs-2.0.0
feat: chore: release fil-proofs-tooling-2.0.0
feat: chore: release storage-proofs-core-2.0.0
feat: chore: release storage-proofs-porep-2.0.0
feat: chore: release storage-proofs-post-2.0.0
docs: update changelog

feat: chore: release 2.0.0

---

storage-proofs/core/src/gadgets/insertion.rs

This PR special-cases insertion when the array size is 2. It is structurally equivalent to the hand-optimized cases already provided for sizes 4 and 8. However, the resulting circuit synthesized is identical to what it replaces, since binary insertion is already optimal and reduces to the case made explicit here.
Note that neither tests counting constraints (throughout the repo) or the CI parameter cache key are modified by this PR. That is because it does not affect circuits.

Help auditors by special-casing binary insert.

---

storage-proofs/porep/src/stacked/vanilla/proof.rs

This is the successor to #1154, now requesting merge into `master`.

Build and load columns in separate threads.

---

CHANGELOG.md
fil-proofs-tooling/Cargo.toml
filecoin-proofs/Cargo.toml
storage-proofs/Cargo.toml
storage-proofs/core/Cargo.toml
storage-proofs/porep/Cargo.toml
storage-proofs/post/Cargo.toml

feat: version bump to v3.0.0

---

.circleci/config.yml

Ain't nobody happy with this anyway

chore(ci): remove validate commit message

---

storage-proofs/porep/src/macros.rs
storage-proofs/porep/src/nse/vanilla/challenges.rs
storage-proofs/porep/src/nse/vanilla/nse.rs
storage-proofs/porep/src/nse/vanilla/porep.rs
storage-proofs/porep/src/nse/vanilla/proof_scheme.rs

updates
- challenge generation
- vanilla proving
- vanilla verification

feat(storage-proofs-porep): implement layer based challenges

---

fil-proofs-tooling/Cargo.toml
filecoin-proofs/Cargo.toml
filecoin-proofs/src/bin/phase2.rs
storage-proofs/core/Cargo.toml
storage-proofs/porep/Cargo.toml
storage-proofs/post/Cargo.toml

Avoid breaking the build on this branch until we have time to rebase it on `master`.

Pin to old deps to fix build without rebase (yet).

---

storage-proofs/core/src/crypto/feistel.rs

test: test if permutation is valid #1193

---

storage-proofs/porep/src/stacked/vanilla/proof.rs

This PR removes the line of dead code noted in #1200.
Closes #1200 .

Remove dead code.

---

fil-proofs-tooling/scripts/run-remote.sh

Metrics capture CI fix, take 2.

fix: Make sure cargo is available on remote machine

---

storage-proofs/porep/src/nse/vanilla/batch_hasher.rs

@DrPeterVanNostrand Does this help?

Refactor batch_hash for clarity.

---

storage-proofs/core/src/gadgets/por.rs
storage-proofs/core/src/hasher/poseidon.rs
storage-proofs/core/src/hasher/types.rs
storage-proofs/porep/Cargo.toml
storage-proofs/porep/src/nse/circuit/circuit.rs
storage-proofs/porep/src/nse/circuit/compound.rs
storage-proofs/porep/src/nse/circuit/hash.rs
storage-proofs/porep/src/nse/circuit/mod.rs
storage-proofs/porep/src/nse/circuit/proof.rs
storage-proofs/porep/src/nse/vanilla/batch_hasher.rs
storage-proofs/porep/src/nse/vanilla/config.rs
storage-proofs/porep/src/nse/vanilla/labels.rs
storage-proofs/porep/src/nse/vanilla/mod.rs
storage-proofs/porep/src/nse/vanilla/nse.rs
storage-proofs/porep/src/nse/vanilla/porep.rs
storage-proofs/porep/src/nse/vanilla/proof_scheme.rs
storage-proofs/porep/src/stacked/circuit/params.rs
storage-proofs/porep/src/stacked/circuit/proof.rs

Squashed and rebased version of #1187

[NSE] Implement circuits

---

README.md

replace `--release--bin` with `--release --bin`

fix Benchmarks examples in README.md

---

storage-proofs/post/src/nse_window/compound.rs
storage-proofs/post/src/nse_window/vanilla.rs

Changes window-post challenge derivation to be agnostic of sector ordering.

fix: nse window-post challenge derivation

---

filecoin-hashers/src/poseidon_types.rs
storage-proofs/porep/src/nse/circuit/circuit.rs
storage-proofs/porep/src/nse/circuit/compound.rs
storage-proofs/porep/src/nse/vanilla/nse.rs
storage-proofs/porep/src/nse/vanilla/porep.rs
storage-proofs/porep/src/nse/vanilla/proof_scheme.rs
storage-proofs/post/src/nse_window/circuit.rs
storage-proofs/post/src/nse_window/compound.rs
storage-proofs/post/src/nse_window/vanilla.rs

- Defines `comm_layers = Poseidon(layer_1_root, ..., layer_14_root)`
- Defines `comm_r = Poseidon(comm_layers, root_r = layer_15_root)`
- Removes layer roots from Window-PoSt public inputs

fix: nse comm_r

---

Cargo.toml
fil-proofs-param/Cargo.toml
fil-proofs-tooling/Cargo.toml
filecoin-hashers/Cargo.toml
filecoin-proofs/Cargo.toml
phase2/Cargo.toml
storage-proofs/core/Cargo.toml
storage-proofs/porep/Cargo.toml
storage-proofs/post/Cargo.toml

Depends on https://github.com/filecoin-project/bellperson/pull/134

feat: update bellperson using new blstrs release

---

.circleci/config.yml
storage-proofs/core/Cargo.toml
storage-proofs/porep/Cargo.toml
storage-proofs/porep/src/stacked/vanilla/proof.rs
storage-proofs/post/Cargo.toml

fix: ensure that builds without gpu work

---

filecoin-proofs/src/api/mod.rs

feat: downgrade verbose logging from info to trace

---

README.md
fil-proofs-tooling/src/bin/benchy/main.rs
storage-proofs-porep/src/stacked/vanilla/proof.rs

docs: add usage notes in the readme
Resolves #1399

feat: split up pc1/pc2 in the window post bench

---

.circleci/config.yml
fil-proofs-param/tests/paramfetch/session.rs
fil-proofs-param/tests/parampublish/support/session.rs
filecoin-hashers/src/blake2s.rs
filecoin-hashers/src/poseidon.rs
filecoin-hashers/src/sha256.rs
filecoin-proofs/tests/mod.rs
fr32/src/reader.rs
storage-proofs-core/src/merkle/builders.rs
storage-proofs-porep/src/stacked/vanilla/proof.rs

feat: upgrade nightly version used in CI
fix: minor updates required for nightly version

fix: remove build warnings

---

Cargo.toml
filecoin-proofs/src/api/seal.rs
filecoin-proofs/tests/api.rs

feat: hash seeds and comm_rs pairwise for bellman API

Updates required to finalize snarkpack support

---

storage-proofs-porep/src/stacked/vanilla/cache.rs
storage-proofs-porep/src/stacked/vanilla/create_label/multi.rs
storage-proofs-porep/src/stacked/vanilla/graph.rs
storage-proofs-porep/src/stacked/vanilla/memory_handling.rs
storage-proofs-porep/src/stacked/vanilla/utils.rs

Reverts filecoin-project/rust-fil-proofs#1477

Revert "Fix: correct usage of BitMask in multicore sdr"

---

storage-proofs-porep/Cargo.toml
storage-proofs-porep/src/stacked/vanilla/cache.rs
storage-proofs-porep/src/stacked/vanilla/proof.rs

revert thread pool changes

---

CHANGELOG.md
fil-proofs-param/Cargo.toml
fil-proofs-tooling/Cargo.toml
filecoin-hashers/Cargo.toml
filecoin-proofs/Cargo.toml
fr32/Cargo.toml
storage-proofs-core/Cargo.toml
storage-proofs-porep/Cargo.toml
storage-proofs-post/Cargo.toml

docs: update changelog for release

feat: update all dependencies for our v10.0.0 release

---

.circleci/config.yml

ci: run gpu tree building tests on all tests

---

fil-proofs-param/Cargo.toml
fil-proofs-param/src/bin/paramcache.rs
fil-proofs-tooling/Cargo.toml
fil-proofs-tooling/src/bin/benchy/main.rs
fil-proofs-tooling/src/bin/check_parameters/main.rs
fil-proofs-tooling/src/bin/gen_graph_cache/main.rs
fil-proofs-tooling/src/bin/gpu-cpu-test/main.rs
fil-proofs-tooling/src/bin/update_tree_r_cache/main.rs
fil-proofs-tooling/src/metadata.rs
filecoin-hashers/Cargo.toml
filecoin-hashers/src/sha256.rs
filecoin-proofs/Cargo.toml
fr32/Cargo.toml
sha2raw/Cargo.toml
sha2raw/src/platform.rs
storage-proofs-core/Cargo.toml
storage-proofs-core/src/crypto/aes.rs
storage-proofs-core/src/crypto/mod.rs
storage-proofs-core/src/settings.rs
storage-proofs-porep/Cargo.toml
storage-proofs-porep/src/stacked/vanilla/challenges.rs
storage-proofs-porep/src/stacked/vanilla/params.rs
storage-proofs-post/Cargo.toml
storage-proofs-update/Cargo.toml

This PR is on an editable branch and replaces #1578 (cc @Stebalien)

Replaces #1578

---

fil-proofs-param/Cargo.toml
fil-proofs-tooling/Cargo.toml
filecoin-proofs/Cargo.toml
fr32/Cargo.toml
sha2raw/Cargo.toml
storage-proofs-core/Cargo.toml
storage-proofs-porep/Cargo.toml
storage-proofs-post/Cargo.toml
storage-proofs-update/Cargo.toml

Remove unused dependencies. 
resolves #1598 .

chore: remove unused dependencies

---

fil-proofs-tooling/Cargo.toml
filecoin-hashers/Cargo.toml
filecoin-hashers/src/poseidon.rs
filecoin-proofs/Cargo.toml
fr32/Cargo.toml
storage-proofs-core/Cargo.toml
storage-proofs-core/src/gadgets/insertion.rs
storage-proofs-core/tests/por_circuit.rs
storage-proofs-core/tests/por_vanilla.rs
storage-proofs-porep/Cargo.toml
storage-proofs-porep/src/stacked/vanilla/proof.rs
storage-proofs-porep/tests/drg_circuit.rs
storage-proofs-porep/tests/stacked_circuit.rs
storage-proofs-post/Cargo.toml
storage-proofs-post/src/election/circuit.rs
storage-proofs-post/src/fallback/circuit.rs
storage-proofs-post/tests/election_circuit.rs
storage-proofs-post/tests/fallback_circuit.rs
storage-proofs-post/tests/rational_circuit.rs
storage-proofs-update/Cargo.toml
storage-proofs-update/src/circuit.rs
storage-proofs-update/src/gadgets.rs
storage-proofs-update/src/poseidon/circuit.rs

Upgrade to `ff` v0.13, which also needs updates to all dependencies that are using `ff`.
BREAKING CHANGE: Changes on the ff traits mean a breaking change.

fix: use newest version of ff

---

README.md

I have fixed the typo error. Please review and merge it.

fix:typo error

---

filecoin-proofs/src/types/porep_config.rs
filecoin-proofs/tests/api.rs

feat: simpify testing of api features
feat: rename aggregate_proofs to aggregate_seal_proofs

Simpify testing of api features

---

Cargo.toml
fil-proofs-param/Cargo.toml
fil-proofs-tooling/Cargo.toml
filecoin-hashers/Cargo.toml
filecoin-proofs/Cargo.toml
fr32/Cargo.toml
sha2raw/Cargo.toml
storage-proofs-core/Cargo.toml
storage-proofs-porep/Cargo.toml
storage-proofs-post/Cargo.toml
storage-proofs-update/Cargo.toml

feat: use workspace inheritance for dependencies
